### ISSUE TITLE
在新版idea中调试拒绝连接

### ISSUE THREAD

**Issue by tinnkm** [alibaba/kt-connect#111]
**Describe the bug**
因为在新版的idea中不再支持JVM Inject插件，所以自己定义了jvm参数-Dhttp.proxyHost=127.0.0.1  -Dhttp.proxyPort=2223，调试时提示time out。

通过ssh方式做测试已经明确可以调通容器内部地址

**Log**
please add -d to debug log
![image](https://user-images.githubusercontent.com/13992692/78113782-d6d9b480-7432-11ea-9d03-35bead5ea995.png)

**Environment (please complete the following information):**
 - OS: [windows server 2012 r2]
 - Kubernetes [v1.17]
 - KT Version [0.0.12]

**Additional context**
![image](https://user-images.githubusercontent.com/13992692/78113937-130d1500-7433-11ea-8f3a-87cbc65ff5e8.png)

**Comment by yunlzheng** [comment]
日志里面看到是ssh命令失败退出了：

```
vpn(ssh) finished.
```

**Comment by tinnkm** [comment]
哪里可以看到详细的日志吗？我重启一个命令窗口,然后在里面执行ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i C:\Users\Administrator/.kt_id_rsa -D 2223 root@127.0.0.1 -p2222，连上去之后，再另起一个命令窗口做测试就可以，但是如果我把ssh关掉，就不通了，你的意思是说kt默认是会开启一个ssh么

**Comment by tinnkm** [comment]
![image](https://user-images.githubusercontent.com/13992692/78115048-ccb8b580-7434-11ea-8f19-5f63517d21ce.png)
我在gitbash中执行了下，测试结果还是和之前一样

**Comment by yunlzheng** [comment]
这部分看日志应该是正常的，你可以现在另外一个terminal中设置http_proxy后验证一下连通性：

> ![image](https://user-images.githubusercontent.com/13992692/78115048-ccb8b580-7434-11ea-8f19-5f63517d21ce.png)
> 我在gitbash中执行了下，测试结果还是和之前一样

**Comment by tinnkm** [comment]
这个我测试过了，是通的，但是在idea里配置http.proxyHost不行

**Comment by JustCoWorker** [comment]
因为IDEA联调用的是SOCKS 协议 ，jvm参数设置: -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=2223

**Comment by tinnkm** [comment]
可以了，谢谢
