### ISSUE TITLE
kt connect plugin release 可执行文件与平台不匹配

### ISSUE THREAD

**Issue by eliu** [alibaba/kt-connect#119]
**Describe the bug**
![image](https://user-images.githubusercontent.com/831707/79285220-8745bf00-7eef-11ea-8328-c03752d94eee.png)

![image](https://user-images.githubusercontent.com/831707/79285259-99276200-7eef-11ea-8cb6-82fb2555004a.png)

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [macOS]
 - KT Version [master, plugin]

**Additional context**

**Comment by yunlzheng** [comment]
@eliu 插件这部分还没有正式release后续会提交到krew的索引上。

**Comment by yunlzheng** [comment]
更新release状态到pre-release, 更新了错误的tgz包
