### ISSUE TITLE
ktctl命令创建的deployment的ImagePullPolicy策略调整

### ISSUE THREAD

**Issue by xianhongdong** [alibaba/kt-connect#128]
能否调整一下shadow的deployment的ImagePullPolicy策略，目前为Always，这在内网环境上影响很大，即使本地已经有相应的镜像，也需要联网下载，导致pod一直在pending状态 。

**Comment by yunlzheng** [comment]
收到，下个版本发布的时候会把这块带上去

**Comment by yunlzheng** [comment]
https://github.com/alibaba/kt-connect/releases/tag/v0.0.13-rc4  0.0.13-rc4的版本中已调整策略

**Comment by little-hang** [comment]
ktctl_0.3.6_Linux_x86_64.tar.gz  这边版本看上去ImagePullPolicy也是Always
