### ISSUE TITLE
windows10不能成功启动kt，日志输出如下就一直卡住了，设置了代理不能访问pod ip

### ISSUE THREAD

**Issue by rrrdddmmm** [alibaba/kt-connect#129]
$ ktctl -d -i kubernetes/kt:stable connect --method=socks5 --dump2hosts
5:21PM INF Connect Start At 7440
5:21PM INF Dump hosts successful.
5:21PM INF Client address 192.168.194.33
5:21PM INF Deploying shadow deployment kt-connect-daemon-ipdvl in namespace default

5:21PM DBG Shadow Pods not ready......
5:21PM INF Shadow Pod status is Pending
5:21PM INF Shadow Pod status is Running
5:21PM INF Shadow is ready.
5:21PM INF Success deploy proxy deployment kt-connect-daemon-ipdvl in namespace default

5:21PM DBG Child, os.Args = [D:\kt\ktctl -d -i kubernetes/kt:stable connect --method=socks5 --dump2hosts]
5:21PM DBG Child, cmd.Args = [kubectl --kubeconfig=C:\Users\renboh\.kube\config -n default port-forward kt-connect-daemon-ipdvl-67f5c459d-n6p5l 2222:22]

**Comment by yunlzheng** [comment]
请检查一下本地kubectl能否正常使用，启动过程依赖了kubectl

**Comment by rrrdddmmm** [comment]
我是在windows10上直接使用的，是不是在windows10上也需要安装kubectl？

**Comment by yunlzheng** [comment]
是的
