### ISSUE TITLE
ktctl_darwin_amd64 do not be recognized to Unix executable file by macOS

### ISSUE THREAD

**Issue by vinci7** [alibaba/kt-connect#13]
**Describe the bug**
ktctl_darwin_amd64 do not be recognized to Unix executable file by macOS

**Log**
无法执行

**Environment (please complete the following information):**
 - OS: Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019;
 - KT Version: 0.0.5

**Additional context**
0.05版本的ktctl_darwin_amd64下载后没有被系统识别为Unix可执行文件，而是文稿类型

`exec kubectl_darwin_amd64` 会导致终端窗口退出

**Comment by yunlzheng** [comment]
Githuab不能直接上传可执行文件，已经修改文档链接以及软件包

**Comment by vinci7** [comment]
谢谢，可以正常使用了
