### ISSUE TITLE
win7 启动成功后，访问pod ip超时

### ISSUE THREAD

**Issue by zbomggg** [alibaba/kt-connect#133]
求教
ssh 127.0.0.1 -p 2222 输入密码后可以连通 connect docker，但是ping pod ip时超时

![image](https://user-images.githubusercontent.com/17559383/81559437-f7961200-93c1-11ea-9a85-2521fd14b391.png)
![image](https://user-images.githubusercontent.com/17559383/81560045-36789780-93c3-11ea-9539-3a05be88b6b1.png)

**Comment by yunlzheng** [comment]
windows下需要配置http_proxy环境变量。

**Comment by zbomggg** [comment]
我命令行中使用了 set http_proxy=socks5://127.0.0.1:2223，但是好像没起作用

**Comment by zbomggg** [comment]
> windows下需要配置http_proxy环境变量。

我命令行中使用了 set http_proxy=socks5://127.0.0.1:2223，但是好像没起作用

**Comment by yunlzheng** [comment]
开一个cmd窗口试试，powershell好像不是这么设置的。

**Comment by zbomggg** [comment]
> 开一个cmd窗口试试，powershell好像不是这么设置的。

我也发现了这个问题，可以了，thks
