### ISSUE TITLE
kt-connect can not support k8s statefulset pod, what can i do to resolve it

### ISSUE THREAD

**Issue by li-zhenlei** [alibaba/kt-connect#136]
**Describe the bug**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by linfan** [comment]
v0.3.0 exchange with selector works with all workloads
