### ISSUE TITLE
退出后无法清理shadow

### ISSUE THREAD

**Issue by JayceLau** [alibaba/kt-connect#147]
**Describe the bug**
如钉钉沟通，pod在未ready或者用golang exec再封装一层后，ctrl+c无法有效的触发clean shadow

**Log**
please add -d to debug log
9:30PM INF pod: sxx-xxx-3470c-kt-jbrqn-74f984bcc7-jng6r is running,but not ready
^C9:30PM INF - Terminal And Clean Workspace

9:30PM INF - start Clean Workspace

9:30PM INF - Successful Clean Up Workspace

**Environment (please complete the following information):**
 - OS: macOS 10.15.6
 - Kubernetes v1.15.6-r1
 - KT Version 0.0.13-rc7

**Additional context**

**Comment by JayceLau** [comment]
请问这个issue有最新进展了吗？

**Comment by linfan** [comment]
已修复
