### ISSUE TITLE
use ktctl connect fail for hostname

### ISSUE THREAD

**Issue by JaneLiuL** [alibaba/kt-connect#149]
**Describe the bug**
11:16AM INF Shadow pod: kt-connect-daemon-dgrcv-67877fdcf9-9gkcp is ready.
11:16AM INF Fail to get pod cidr from node.Spec.PODCIDR, try to get with pod sample
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
11:16AM INF port-forward start at pid: 16906
Traceback (most recent call last):
  File "/usr/bin/sshuttle", line 5, in <module>
    from sshuttle.cmdline import main
  File "/usr/lib/python2.7/site-packages/sshuttle/cmdline.py", line 5, in <module>
    import sshuttle.client as client
  File "/usr/lib/python2.7/site-packages/sshuttle/client.py", line 302
    assert(not re.search(rb'[^-\w\.]', hostname))
                                    ^

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: CentOS Linux 7 (Core
 - Kubernetes: v1.16.9
 - KT Version kt-0.0.12

**Additional context**

**Comment by JaneLiuL** [comment]
Fix this issue now, I check the sshuttle, actually the local VM need to install sshuttle, but have to use Python3.5+
My VM is only python2, that's why will fail.
You could close this issue now

**Comment by hillbun** [comment]
@JaneLiuL 

How to fix this issue if only python2 installed?
