### ISSUE TITLE
本地VM使用ktctl成功之后，使用curl访问集群网络失败说解释地址失败

### ISSUE THREAD

**Issue by JaneLiuL** [alibaba/kt-connect#150]
**Describe the bug**
现在我使用ktctl在本地连接集群，看上去没有报错，可是使用curl却说不能解释地址
![image](https://user-images.githubusercontent.com/56822274/90485690-71c8f600-e16a-11ea-8f75-192148496859.png)
然后成功之后，我再打开一个窗口
curl app-js:8080/demo
curl: (6) Could not resolve host: app-js; Name or service not known
或者尝试curl app-js.jane-test:8080/demo
curl: (6) Could not resolve host: app-js.jane-test; Name or service not known

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: Redhat 7.6 (Maipo)
 - Kubernetes v1.16.9
 - KT Version kt-0.0.12

**Additional context**

**Comment by yunlzheng** [comment]
看日志里面sshuttle报错，建议根据这个文档先排查一下环境是否正确配置： https://alibaba.github.io/kt-connect/#/zh-cn/troubleshoot

**Comment by JaneLiuL** [comment]
跟着文档走，卡住在这里，试过写这台VM本身的密码，也试过空密码，也试过123456
# ssh-copy-id root@127.0.0.1 -p 2222
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@127.0.0.1's password: 
Permission denied, please try again.
root@127.0.0.1's password: 
Permission denied, please try again.
root@127.0.0.1's password: 
Permission denied (publickey,password)

另外，我想问问我的截图里面没看出是sshuttle报错，请问你的日志是哪里看出来的？

**Comment by yunlzheng** [comment]
日志里面显示是sshuttle进行退出了，加上-d参数可以看到详细信息：
ktctl -d connect

**Comment by JaneLiuL** [comment]
加上-d如下，您的意思是，vpn(sshuttle) finished就是退出的意思对吗？
那请问我应该如何进行下一步？
# ktctl --label virtual-env=dev.proj2 --namespace jane-test -d connect 
10:53AM INF Connect Start At 19728
10:53AM INF Client address 10.120.14.52
10:53AM INF deploy shadow deployment kt-connect-daemon-qynzj in namespace jane-test

10:53AM INF pod label: kt=kt-connect-daemon-qynzj
10:53AM INF pod:  is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is running,but not ready
10:53AM INF Shadow pod: kt-connect-daemon-qynzj-f499dbb45-g8b7b is ready.
10:53AM INF Fail to get pod cidr from node.Spec.PODCIDR, try to get with pod sample
10:53AM DBG Child, os.Args = [ktctl --label virtual-env=dev.proj2 --namespace jane-test -d connect]
10:53AM DBG Child, cmd.Args = [kubectl --kubeconfig=/root/.kube/config -n jane-test port-forward kt-connect-daemon-qynzj-f499dbb45-g8b7b 2222:22]
10:53AM INF port-forward start at pid: 19884
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
10:53AM DBG Child, os.Args = [ktctl --label virtual-env=dev.proj2 --namespace jane-test -d connect]
10:53AM DBG Child, cmd.Args = [sshuttle --dns --to-ns 10.0.16.92 -v -e ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /root/.kt_id_rsa -r root@127.0.0.1:2222 -x 127.0.0.1 10.0.0.0/16 10.50.0.0/16]
10:53AM INF KT proxy start successful
10:53AM INF vpn(sshuttle) finished

**Comment by JaneLiuL** [comment]
我换了一套集群，然后按照https://alibaba.github.io/kt-connect/#/zh-cn/troubleshoot走是可以走完整个过程，但仍然是DNS解析有问题，我的local的VM是有私有DNS服务器的，请问是否跟这个有关呢？
curl app-js.jane-test:8080/demo
curl: (6) Could not resolve host: app-js.jane-test; Name or service not known
# curl app-js:8080/demo
curl: (6) Could not resolve host: app-js; Name or service not known

**Comment by JaneLiuL** [comment]
你可以close这个issue了，我切换一个本地虚拟机就没问题，判断是我上面用的那台机器应该是公司网络层面有一些限制之类。
