### ISSUE TITLE
域名解析未添加对statesetful支持

### ISSUE THREAD

**Issue by 784134748** [alibaba/kt-connect#156]
**Describe the bug**
当使用statesetful方式进行部署时
使用：mysql-0.mysql-hs访问会被被解析成mysql-0.mysql-hs.svc.cluster.local.
完整的域名应当是：mysql-0.mysql-hs.canal.svc.cluster.local

**Environment (please complete the following information):**
 - OS: mac os
 - Kubernetes: 1.16.5 
 - KT Version: 0.0.13-rc9

**Comment by linfan** [comment]
fixed by 57fc60ec4403c0192244c66a06b796143033d79e
