### ISSUE TITLE
本地调试两个相同版本的服务时，报configMap已存在

### ISSUE THREAD

**Issue by JayceLau** [alibaba/kt-connect#157]
**Describe the bug**
本地调试两个服务，通过--version传入相同的值，会报configMap已存在。由于configMap只拼接了--version，未拼接随机字符串导致。

**Log**
please add -d to debug log
5:40PM ERR configmaps "kt-mesh-public-key-z006587" already exists

**Environment (please complete the following information):**
 - OS: macOS 10.15.6
 - Kubernetes:  v1.15.6-r1
 - KT Version 0.0.13-rc7

**Additional context**
想了解一下，通过--label传入一个名字为version的标签和通过--version设置版本，有什么区别？

**Comment by yunlzheng** [comment]
本地的两个服务都是映射到集群中的同一个Service?  如果是一个服务的不同版本的话version不能重复。 如果是分别是两个服务，那应该mesh到集群中的不同Service。

--label和--version都能到达指定version的目的，不过mesh场景建议用--version, 语义更好一点

**Comment by JayceLau** [comment]
分别是两个服务，也mesh到了不同的service，只是对应的configMap kt-mesh-public-key-XXXXX只拼接了version字段，如果指定了相同的version，configMap肯定就重名了。

**Comment by JayceLau** [comment]
pkg/kt/cluster/kubernetes.go:89
```	
component, version := labels["kt-component"], labels["version"]
sshcm = fmt.Sprintf("kt-%s-public-key-%s", component, version)
```
这个地方，只拼接了kt组件名和版本号，未拼接随机字符串，导致了相同版本无法创建sshcm
