### ISSUE TITLE
UI项目在哪里？是否开源？

### ISSUE THREAD

**Issue by dayuoba** [alibaba/kt-connect#16]
**Is your feature request related to a problem? Please describe.**
我们需要额外开发一些ui功能，请问是否开源UI项目？这样我们可以把一些通用功能提交PR。比如相关的鉴权功能等

**Comment by yunlzheng** [comment]
后续会开放UI的源码~

**Comment by dayuoba** [comment]
好的，会发布到这个项目中还是单独起一个项目？我订阅一下

**Comment by yunlzheng** [comment]
@dayuoba 会合并在一个项目里面

**Comment by yunlzheng** [comment]
@dayuoba dashboard项目和对应的后端已经合并到master。
