### ISSUE TITLE
如果 service 的 targetport 是通过 port name 与 pod 绑定的，ktctl exchange 替换后 service 无法选中 pod

### ISSUE THREAD

**Issue by lyyyuna** [alibaba/kt-connect#172]
**Describe the bug**

1. 对应 pod 中 port 定义含有 name
2. service 中 targetport 写的是 pod 中对应 port 的 name
3. kt exchange 后，对应替换的 pod 中没有该 port name 的定义，导致 service 无法选中 pod

**Environment (please complete the following information):**
 - Kubernetes [1.16.8]
 - KT Version [0.0.12]

**Additional context**

**Comment by linfan** [comment]
@hr3685930 @lyyyuna 
已在 0.3.3-beta2 版本中修复
https://github.com/alibaba/kt-connect/releases/tag/v0.3.3-beta2

exchange/mesh时候指定相应数值端口号即可，会自动处理端口名到端口号的转换

**Comment by linfan** [comment]
0.3.3 正式版已发布
