### ISSUE TITLE
windows环境socks5,cluster dns

### ISSUE THREAD

**Issue by OnlyGeek** [alibaba/kt-connect#175]
增加windows环境利用socks5调试,headless服务.
dumphosts这种方法有点小坑

**Comment by linfan** [comment]
dumphosts主要是解决域名解析默认不会通过socks5代理的问题。
不太理解你的描述，可以具体说一下遇到的情况吗？

**Comment by OnlyGeek** [comment]
headless服务没有cluster ip, 导致dunmphosts无法写hosts文件记录. 所以环境中的每个服务要通过服务名调试的话, 都得加上cluster ip
