### ISSUE TITLE
通过vpn模式时，希望获取vpn的连接信息，这样可以使用wifi路由器配置，个人计算机无需配置即可连接集群网络。

### ISSUE THREAD

**Issue by weihai4099** [alibaba/kt-connect#177]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by linfan** [comment]
`vpn`模式的实际上并不是通用的VPN，实际是利用iptables规则实现的类似VPN效果，不存在VPN连接信息

**Comment by weihai4099** [comment]
Thanks
