### ISSUE TITLE
Agent for kt-connect rather than connect to k8s cluster directly

### ISSUE THREAD

**Issue by yeqown** [alibaba/kt-connect#178]
**Is your feature request related to a problem? Please describe.**
1. DO NOT allow any developer can visit the k8s cluster.
2. NOT all developers know k8s well.

**Describe the solution you'd like**
1. Using the agent instead of `kt-connect` for developer to connect to k8s cluster
2. The agent would be running on a middleman machine.
3. Agent should be simple to use with little config [middleman ssh config, I would compile these into binary ~ ]

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by linfan** [comment]
kt-connect v0.3.0 and above would not need manually setup proxy any more, no middleman machine needed neight.
