### ISSUE TITLE
在windows环境使用时，可以访问集群应用，无法ping通pod

### ISSUE THREAD

**Issue by Daose1997** [alibaba/kt-connect#182]
`?[90m2:37PM?[0m ?[32mINF?[0m Connect Start At 13684
?[90m2:37PM?[0m ?[32mINF?[0m Client address 192.168.72.170
?[90m2:37PM?[0m ?[32mINF?[0m deploy shadow deployment kt-connect-daemon-bndnx in namespace default
?[90m2:37PM?[0m ?[32mINF?[0m Shadow pod: kt-connect-daemon-bndnx-68644cb456-dbxh5 is ready.
?[90m2:37PM?[0m ?[33mDBG?[0m Child, os.Args = [ktctl -d -i 192.168.26.116:5000/rdc-incubator/kt-connect-shadow:stable connect --method=socks5]
?[90m2:37PM?[0m ?[33mDBG?[0m Child, cmd.Args = [kubectl --kubeconfig=C:\Users\violet\.kube\config -n default port-forward kt-connect-daemon-bndnx-68644cb456-dbxh5 2222:22]
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
?[90m2:37PM?[0m ?[32mINF?[0m port-forward start at pid: 18464
?[90m2:37PM?[0m ?[32mINF?[0m ==============================================================
?[90m2:37PM?[0m ?[32mINF?[0m Start SOCKS5 Proxy: export http_proxy=socks5://127.0.0.1:2223
?[90m2:37PM?[0m ?[32mINF?[0m ==============================================================
?[90m2:37PM?[0m ?[33mDBG?[0m Child, os.Args = [ktctl -d -i 192.168.26.116:5000/rdc-incubator/kt-connect-shadow:stable connect --method=socks5]
?[90m2:37PM?[0m ?[33mDBG?[0m Child, cmd.Args = [ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i C:\Users\violet/.kt_id_rsa -D 2223 root@127.0.0.1 -p2222 sh loop.sh]
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
GetConsoleMode on STD_INPUT_HANDLE failed with 6

?[90m2:37PM?[0m ?[32mINF?[0m vpn(ssh) start at pid: 22652
?[90m2:37PM?[0m ?[32mINF?[0m KT proxy start successful
`

使用curl可以直接访问集群应用，获取返回值，但是ping ip的时候超时

**Comment by tiechaoyang** [comment]
你解决了嘛？另外是怎么用 crul访问集群应用的

**Comment by linfan** [comment]
目前只有Linux下的tun模式（`ktctl connect --method=tun`）支持本地到集群的ping请求，Windows不支持此模式，也不支持ping集群IP

**Comment by linfan** [comment]
v0.3.0 版本已支持
