### ISSUE TITLE
项目是否还在维护？

### ISSUE THREAD

**Issue by muyu66** [alibaba/kt-connect#183]
**Describe the bug**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by linfan** [comment]
项目成员都还在，暂时没有足够精力投入，会择期重启~
