### ISSUE TITLE
exchang 连接异常退出

### ISSUE THREAD

**Issue by kenneys** [alibaba/kt-connect#186]
**Describe the bug**
/.ktctl/exchange/kt_bpsen_id_rsa -R 8180:127.0.0.1:8180 root@127.0.0.1 -p2282 sh loop.sh]
Handling connection for 2282
E0326 20:22:21.844829   46628 portforward.go:400] an error occurred forwarding 2282 -> 22: error forwarding port 22 to pod ae2385931a6e80cb87171cf5e03fafc9f8efa99580ded254465e4a696f9df4df, uid : unable to do port forwarding: socat not found.
ssh_exchange_identification: Connection closed by remote host
[90m8:22PM[0m [32mINF[0m ssh remote port-forward start at pid: 93488
[90m8:22PM[0m [1m[31mERR[0m[0m background process of ssh remote port-forward failed [31merror=[0m[31m"exit status 255"[0m
[90m8:22PM[0m [1m[31mERR[0m[0m invalid argument
[90m8:22PM[0m [32mINF[0m - start Clean Workspace

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by linfan** [comment]
Fixed，已移除ssh命令行工具依赖
