### ISSUE TITLE
当dns返回的类型是cname的时候，convertAnswert替换了cname域名为查询域名导致问题

### ISSUE THREAD

**Issue by yxing-xyz** [alibaba/kt-connect#190]
**Describe the bug**
当dns返回的类型是cname的时候，convertAnswert替换了cname域名为查询域名导致问题

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04] Linux Chromium
 - Kubernetes [e.g. 1.10.1] 1.18	
 - KT Version [e.g. 0.0.4] latest
 
**Additional context**
linux chromium认为替换了cname域名的dns协议不规范：DNS_PROBE_FINISHED_NXDOMAIN

**Comment by linfan** [comment]
已在 0.3.3-beta2 版本中修复
https://github.com/alibaba/kt-connect/releases/tag/v0.3.3-beta2

**Comment by linfan** [comment]
0.3.3 正式版已发布
