### ISSUE TITLE
kt-dev 钉钉群二维码可以再贴一下吗？

### ISSUE THREAD

**Issue by jimtang9527** [alibaba/kt-connect#191]
**Describe the bug**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**
这是个很好的项目，怎么没人维护啊。阿里内部也应该会用的。开发k8s微服务很需要的。

**Comment by yunlzheng** [comment]
README 已更新
