### ISSUE TITLE
Mesh： 基于服务网格的开发测试 --> 部署服务网格定义

### ISSUE THREAD

**Issue by DevialWarrior** [alibaba/kt-connect#192]
**Describe the bug**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**
文件名写错了，应该是 tomcat7-istio.yaml
![image](https://user-images.githubusercontent.com/22161835/114336876-86874d80-9b82-11eb-8de6-ede8f91a8f93.png)

**Comment by linfan** [comment]
fixed
