### ISSUE TITLE
在connect 模式下，使用 restemplate 请求k8s内部服务的restful API 出现错误 java.net.UnknownHostException

### ISSUE THREAD

**Issue by DevialWarrior** [alibaba/kt-connect#193]
**Describe the bug**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**
在connect 模式下，使用 restemplate 请求k8s内部服务的restful API 出现错误 java.net.UnknownHostException。
但是使用 cn.hutool.http.HttpRequest 发送请求可以的到反馈。

**Comment by linfan** [comment]
可尝试更新到v0.3.0版本
