### ISSUE TITLE
生成shadow pod的命令中，怎么指定label？ 即，想指定tomcat-kt-bagbo 中的bagbo

### ISSUE THREAD

**Issue by ysjzxyk** [alibaba/kt-connect#194]

**Comment by yunlzheng** [comment]
ktctl --help 其中--label参数可以指定生成pod的标签

**Comment by ysjzxyk** [comment]
![image](https://user-images.githubusercontent.com/26375272/114979927-41368900-9ebe-11eb-9e41-442d7dd9e412.png)

这么用的，没有生效：ktctl --label test --kubeconfig $mesh_config -n crm-test mesh biz-crm-msg-center-push --expose 8011
