### ISSUE TITLE
podLabels 添加 pod选择器 有问题。

### ISSUE THREAD

**Issue by sg6303** [alibaba/kt-connect#195]
**Describe the bug**
在 kt/cluster/kubernetes.go 文件 第 326 行。podLabels.Add(*requirement) 无法将选择器添加进去

**Log**
please add -d to debug log
![image](https://user-images.githubusercontent.com/3842903/115984723-36c17100-a5db-11eb-88e2-6428d8517ef0.png)

![image](https://user-images.githubusercontent.com/3842903/115984748-4ccf3180-a5db-11eb-91df-16a63160cd54.png)

执行之后，podLabels 还是为空的

**Comment by linfan** [comment]
已修复，当前版本已支持`--withLabel`参数为pod添加自定义label
