### ISSUE TITLE
fail create ssh connection dial tcp 127.0.0.1:2222: connect: connection refused

### ISSUE THREAD

**Issue by liuyq913** [alibaba/kt-connect#203]
**Describe the bug**
执行，ktctl -d connect --method=socks5 命令，fail create ssh connection dial tcp 127.0.0.1:2222: connect: connection refused

**Log**
10:16AM INF Connect Start At 1662
10:16AM INF private Key generated
10:16AM INF public key generated
10:16AM INF successful create ssh config map kt-connect-public-key-qftzg
10:16AM INF Client address 192.168.93.226
10:16AM DBG create shadow with debug mode
10:16AM INF shadow template is prepare ready.
10:16AM INF deploy shadow deployment kt-connect-daemon-qftzg in namespace default

10:16AM INF pod label: kt=kt-connect-daemon-qftzg
10:16AM INF pod: kt-connect-daemon-qftzg-7dd7b8ffc5-qkzz4 is running,but not ready
10:16AM INF pod: kt-connect-daemon-qftzg-7dd7b8ffc5-qkzz4 is running,but not ready
10:16AM INF Shadow pod: kt-connect-daemon-qftzg-7dd7b8ffc5-qkzz4 is ready.
10:16AM DBG Child, os.Args = [ktctl -d connect --method=socks5]
10:16AM DBG Child, name = port-forward, cmd.Args = [kubectl port-forward kt-connect-daemon-qftzg-7dd7b8ffc5-qkzz4 2222:22]
10:16AM INF port-forward start at pid: 1666
10:16AM INF wait(0s) port-forward successful
10:16AM INF ==============================================================
10:16AM INF Start SOCKS5 Proxy Successful: export http_proxy=socks5://127.0.0.1:2223
10:16AM INF ==============================================================
10:16AM ERR fail create ssh connection dial tcp 127.0.0.1:2222: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e3c1ba]

goroutine 1 [running]:
github.com/alibaba/kt-connect/pkg/kt/channel.(*SSHChannel).StartSocks5Proxy(0x2f2e8d8, 0xc0001d62d0, 0xc0004d82c0, 0xe, 0xc0004d82e0, 0xe, 0x245b820, 0xc0005c2000)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/channel/ssh.go:21 +0xaa
github.com/alibaba/kt-connect/pkg/kt/connect.startSocks5Connection(0x2463280, 0x2f2e8d8, 0xc00012cdc0, 0xc0006b6e80, 0x2484cc0)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/connect/outbound.go:81 +0x4f1
github.com/alibaba/kt-connect/pkg/kt/connect.outbound(0xc00000e028, 0xc0004c1020, 0x28, 0xc000690f70, 0xb, 0xc0004d06f0, 0xc0003237a0, 0x11, 0x12, 0x2484cc0, ...)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/connect/outbound.go:60 +0x39f
github.com/alibaba/kt-connect/pkg/kt/connect.(*Shadow).Outbound(0xc00000e028, 0xc0004c1020, 0x28, 0xc000690f70, 0xb, 0xc0004d06f0, 0xc0003237a0, 0x11, 0x12, 0x2484cc0, ...)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/connect/outbound.go:22 +0xcc
github.com/alibaba/kt-connect/pkg/kt/command.connectToCluster(0x2484c80, 0xc0000b1530, 0xc00012cdc0, 0x22413b7, 0x7)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/connect.go:114 +0xb54
github.com/alibaba/kt-connect/pkg/kt/command.(*Action).Connect(0xc000483cc0, 0x2484c80, 0xc0000b1530, 0xc00012cdc0, 0xc000483cf0, 0xc000483d18)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/connect.go:40 +0xd0
github.com/alibaba/kt-connect/pkg/kt/cmd.(*ConnectOptions).Run(0xc0000a06e0, 0xc0000fe580, 0xc000370b40)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/cmd/cmd.go:144 +0xbf
github.com/alibaba/kt-connect/pkg/kt/cmd.NewConnectCommand.func1(0xc0000fe580, 0xc000370b40, 0x1, 0x3, 0x0, 0x0)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/cmd/cmd.go:71 +0x78
github.com/spf13/cobra.(*Command).execute(0xc0000fe580, 0xc00009a090, 0x3, 0x3, 0xc0000fe580, 0xc00009a090)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fe580, 0xc0000b0000, 0x245bb40, 0xc0000b0008)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/runner/work/kt-connect/kt-connect/cmd/kubectl-connect/main.go:22 +0x126

**Environment (please complete the following information):**
 - OS: [macOS 10.14 ]
 - Kubernetes [v1.18.3]
 - KT Version [0.0.13-rc11]

**Additional context**

**Comment by xyz-li** [comment]
使用--waitTime参数， 指定等待时间。

**Comment by xyz-li** [comment]
Resolved by #212
