### ISSUE TITLE
对于异常或者强退，导致kt-connect容器未被销毁，有什么解决方案嘛

### ISSUE THREAD

**Issue by muyu66** [alibaba/kt-connect#204]
对于异常或者强退，导致kt-connect容器未被销毁，有什么解决方案嘛。

**Comment by linfan** [comment]
计划会增加一个清理命令，细节待讨论确认

**Comment by linfan** [comment]
@muyu66 [0.1.0-rc1版本](https://github.com/alibaba/kt-connect/releases/tag/v0.1.0-rc1)已添加`clean`命令，可以先试用了，不需要额外参数，清理功能只对kt-connect `0.1.0-rc1`及之后版本创建的容器有效。详细文档会在`0.1.0`版本正式发布的时候补上。
