### ISSUE TITLE
windows环境下不能访问集群

### ISSUE THREAD

**Issue by 497010477** [alibaba/kt-connect#224]
我在linux环境跟着connect故障排查的步骤执行，是没有问题的，但是切换到windows就不行了，在执行curl之前的步骤都是没有报错的，如图

![image](https://user-images.githubusercontent.com/26075179/126511910-c0f87bfa-6edb-4eb3-98de-de86a041f4fd.png)

![image](https://user-images.githubusercontent.com/26075179/126511966-f78e49df-dbb7-49e2-9172-1dd03ba19ab5.png)

但是在执行curl的时候报错了，

![image](https://user-images.githubusercontent.com/26075179/126512103-aadcfb17-d837-4fba-a52e-f2c6cd459ea8.png)

附上我在windows环境按照kt connect执行的结果与：
![image](https://user-images.githubusercontent.com/26075179/126513078-19c4978e-c61a-4741-82a6-4d214d5e8ed6.png)
![image](https://user-images.githubusercontent.com/26075179/126513765-680db00f-e3ac-4c68-897a-616c6a43d9df.png)

**Comment by 497010477** [comment]
我认为是由于window的某些系统设置导致的，但是我觉得这种设置步骤应该在文档里有体现，另外附上一些版本信息，kubectl是为了调试目的单独安装的
![image](https://user-images.githubusercontent.com/26075179/126515424-b258cb37-8454-448f-8988-0eabd8f7dd78.png)
![image](https://user-images.githubusercontent.com/26075179/126515631-67375ebb-b5cb-4a3c-861c-26dcc29faf20.png)
![image](https://user-images.githubusercontent.com/26075179/126515738-f24b8052-e813-403e-be62-2d32c0d74eb7.png)
防火墙已关闭
![image](https://user-images.githubusercontent.com/26075179/126515834-438154d7-d452-47ed-a240-82b51b6df72a.png)

**Comment by wp763691** [comment]
解决了吗，我 也是同样的问题

**Comment by linfan** [comment]
在Windows下如果要通过curl验证网络连接，需要额外设置`HTTP_PROXY`环境变量，在[Windows支持](http://localhost:3000/#/zh-cn/guide/windows-support)文档中有介绍，具体命令为：

- cmd：`set HTTP_PROXY=socks5://127.0.0.1:2223`
- powershell：`$env:HTTP_PROXY=socks5://127.0.0.1:2223`

KtConnect对Windows的支持在即将发布的`v0.1.0`版本中会有较大改进，敬请关注近期的新版发布和文档内容变更。

**Comment by 497010477** [comment]
> 在Windows下如果要通过curl验证网络连接，需要`HTTP_PROXY`额外设置环境变量，在[Windows](http://localhost:3000/#/zh-cn/guide/windows-support)文档[支持下](http://localhost:3000/#/zh-cn/guide/windows-support)具体介绍，具体为：
> 
> * 指令：`set HTTP_PROXY=socks5://127.0.0.1:2223`
> * 电源外壳：`$env:HTTP_PROXY=socks5://127.0.0.1:2223`
> 
> KtConnect 即将发布的`v0.1.0`版本中将有支持改进，即将发布的新版本和文档内容更改。

**Comment by 497010477** [comment]
> 在Windows下如果要通过curl验证网络连接，需要额外设置`HTTP_PROXY`环境变量，在[Windows支持](http://localhost:3000/#/zh-cn/guide/windows-support)文档中有介绍，具体命令为：
> 
> * cmd：`set HTTP_PROXY=socks5://127.0.0.1:2223`
> * powershell：`$env:HTTP_PROXY=socks5://127.0.0.1:2223`
> 
> KtConnect对Windows的支持在即将发布的`v0.1.0`版本中会有较大改进，敬请关注近期的新版发布和文档内容变更。

        你好，我最终机缘巧合的解决了这个问题，我初次连接有问题时，是在进行2222端口转发的时候直接finish了，端口并没有打开，问题中kt connect的正确执行结果是在我跟随connect问题调试步骤后，经过我的确认，我把自己下载kubectl从PATH路径移出后，仍能复现最初的端口转发时不能成功打开端口的情况，所以我对此的判断是在我的windows系统中，ktctl内置的kubectl命令没有打开端口的权限，当时当我的PATH路径中有自己下载的kubectl程序后，就能够成功打开端口了。我的同事也有大量存在类似的情况，我通过同样的方式帮助他们解决了问题（权限不足的原因我还不清楚）。对此我的想法和建议是，在kt connect执行过程中，对每个命令的执行结果进行判断，如果不符合预期，在命令行中抛出错误，让用户能够快速感知到运行是不正常的。对于技术人员而言，没有ERROR通常意味着没有问题，但是实际情况是kt connect并没有连上集群。另外一点是，针对这种常见情况，建议在对windows支持的有所优化，或者至少给文档补充相应的处理手段。

        另外一点关于curl，我在cmd里验证成功了，我当时判断出了和powershell有很大关系。相信如你所说，两个程序的设置代理的方式有所不同，不过因为set命令powershell没有报错，所以我没有意识到有问题。不过不凑巧的是，我刚刚在powershell里尝试了$env:HTTP_PROXY=socks5://127.0.0.1:2223命令，curl仍然不通，不过这已经不影响我的使用了。如果可以的话，在文档里能明确指出使用cmd而非powershell我相信是最好不过了。
        我在kt connect的使用上似乎碰巧踩了足够多的坑，导致调试过程给我带来了很多的迷惑和不理解，也花费了我一些时间。所以我希望能够采纳我的想法与建议，来为其他朋友们避免类似的情况。

**Comment by 497010477** [comment]
> 解决了吗，我 也是同样的问题

        你好，我最终机缘巧合的解决了这个问题，我初次连接有问题时，是在进行2222端口转发的时候直接finish了，端口并没有打开，问题中kt connect的正确执行结果是在我跟随connect问题调试步骤后，经过我的确认，我把自己下载kubectl从PATH路径移出后，仍能复现最初的端口转发时不能成功打开端口的情况，所以我对此的判断是在我的windows系统中，ktctl内置的kubectl命令没有打开端口的权限，当时当我的PATH路径中有自己下载的kubectl程序后，就能够成功打开端口了。我的同事也有大量存在类似的情况，我通过同样的方式帮助他们解决了问题（权限不足的原因我还不清楚）。对此我的想法和建议是，在kt connect执行过程中，对每个命令的执行结果进行判断，如果不符合预期，在命令行中抛出错误，让用户能够快速感知到运行是不正常的。对于技术人员而言，没有ERROR通常意味着没有问题，但是实际情况是kt connect并没有连上集群。另外一点是，针对这种常见情况，建议在对windows支持的有所优化，或者至少给文档补充相应的处理手段。

        另外一点关于curl，我在cmd里验证成功了，我当时判断出了和powershell有很大关系。相信如你所说，两个程序的设置代理的方式有所不同，不过因为set命令powershell没有报错，所以我没有意识到有问题。不过不凑巧的是，我刚刚在powershell里尝试了$env:HTTP_PROXY=socks5://127.0.0.1:2223命令，curl仍然不通，不过这已经不影响我的使用了。如果可以的话，在文档里能明确指出使用cmd而非powershell我相信是最好不过了。
        我在kt connect的使用上似乎碰巧踩了足够多的坑，导致调试过程给我带来了很多的迷惑和不理解，也花费了我一些时间。所以我希望能够采纳我的想法与建议，来为其他朋友们避免类似的情况。

**Comment by 497010477** [comment]
> 解决了吗，我 也是同样的问题

        你好，我最终机缘巧合的解决了这个问题，我初次连接有问题时，是在进行2222端口转发的时候直接finish了，端口并没有打开，问题中kt connect的正确执行结果是在我跟随connect问题调试步骤后，经过我的确认，我把自己下载kubectl从PATH路径移出后，仍能复现最初的端口转发时不能成功打开端口的情况，所以我对此的判断是在我的windows系统中，ktctl内置的kubectl命令没有打开端口的权限，当时当我的PATH路径中有自己下载的kubectl程序后，就能够成功打开端口了。我的同事也有大量存在类似的情况，我通过同样的方式帮助他们解决了问题（权限不足的原因我还不清楚）。对此我的想法和建议是，在kt connect执行过程中，对每个命令的执行结果进行判断，如果不符合预期，在命令行中抛出错误，让用户能够快速感知到运行是不正常的。对于技术人员而言，没有ERROR通常意味着没有问题，但是实际情况是kt connect并没有连上集群。另外一点是，针对这种常见情况，建议在对windows支持的有所优化，或者至少给文档补充相应的处理手段。

        另外一点关于curl，我在cmd里验证成功了，我当时判断出了和powershell有很大关系。相信如你所说，两个程序的设置代理的方式有所不同，不过因为set命令powershell没有报错，所以我没有意识到有问题。不过不凑巧的是，我刚刚在powershell里尝试了$env:HTTP_PROXY=socks5://127.0.0.1:2223命令，curl仍然不通，不过这已经不影响我的使用了。如果可以的话，在文档里能明确指出使用cmd而非powershell我相信是最好不过了。
        我在kt connect的使用上似乎碰巧踩了足够多的坑，导致调试过程给我带来了很多的迷惑和不理解，也花费了我一些时间。所以我希望能够采纳我的想法与建议，来为其他朋友们避免类似的情况。

**Comment by linfan** [comment]
反馈收到。

在当前版本里ktctl实际上是直接依赖本地kubectl的（我们正在尝试移除这个依赖），到目前为止，如果PATH中找不到kubectl命令时，执行一定会出错。对于执行报错信息不清晰的问题，会在接下来`0.1.x`版本的重构过程里逐步处理掉。

PowerShell设置环境变量`$env:HTTP_PROXY="socks5://127.0.0.1:2223"`命令是没有问题的，不过`curl`在PowerShell里和一个内置的命令冲突了，如果要访问Web服务的话，需要写`curl.exe <服务地址>`。关于PowerShell下的使用，也会在近期统一更新到文档里。
