### ISSUE TITLE
考虑支持 headless Service嘛

### ISSUE THREAD

**Issue by muyu66** [alibaba/kt-connect#237]
比如一些持久化服务，一般都是以headless提供出来的。

**Comment by linfan** [comment]
默认就支持headless service的哦~ 如果有遇到问题，可以把详细过程描述一下

**Comment by linfan** [comment]
哦，windows下确实一直还没支持headless service。近期我们正在尝试在windows场景上引入wireguard方案，这个方案会顺带解决headless service访问的问题，再等等哈

**Comment by muyu66** [comment]
对的，是windows，我误以为linux也是不支持。

**Comment by muyu66** [comment]
有进展嘛？ktctl 0.2.0好像尚未支持
