### ISSUE TITLE
failed to dial 22: dial tcp4 127.0.0.1:22: connect: connection refused

### ISSUE THREAD

**Issue by Coll-sy** [alibaba/kt-connect#238]
PS C:\Users\xxx> ktctl -d connect --method socks5
9:11PM INF KtConnect start at 5864
9:11PM DBG Search service in default namespace...
9:11PM DBG Service found: kubernetes.default xx.xx.xx.xx
9:11PM INF Dump hosts successful
9:11PM INF Private Key generated
9:11PM INF Public key generated
9:11PM INF Successful create ssh config map kt-connect-public-key-yxfc
9:11PM INF Client address xx.xx.xx.xx
9:11PM DBG Create shadow with debug mode
9:11PM INF Shadow template is prepare ready.
9:11PM INF Deploy shadow deployment kt-connect-daemon-yxfct in namespace default
9:11PM INF Pod: kt-connect-daemon-yxfct-xxxxxxxxxxxxx is running, but not ready
9:11PM INF Pod: kt-connect-daemon-yxfct-xxxxxxxxxxxxx is running, but not ready
9:11PM INF Pod: kt-connect-daemon-yxfct-xxxxxxxxxxxxx is running, but not ready
9:11PM INF Shadow pod: kt-connect-daemon-yxfct-xxxxxxxxxxxxx is ready.
9:11PM INF Scan proxy CIDR in namespace scope
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
Handling connection for 2222
9:11PM INF Connect to port-forward successful
9:11PM INF Starting up socks5 proxy ...
Handling connection for 2222
E0810 21:11:44.962841    5864 portforward.go:400] an error occurred forwarding 2222 -> 22: error forwarding port 22 to pod d70736866ccb84cc6b1e2cb4fbb12d024480f6998778a8xxxxxxxxxxxxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-b3405187-2938-37fd-b418-xxxxxxxxxxxxx": failed to dial 22: dial tcp4 127.0.0.1:22: connect: connection refused
E0810 21:11:44.962841    5864 portforward.go:400] an error occurred forwarding 2222 -> 22: error forwarding port 22 to pod d70736866ccb84cc6b1e2cb4fbb12d024480f6998778a85a1xxxxxxxxxxxxx, uid : failed to execute portforward in network namespace "/var/run/netns/cni-b3405187-2938-37fd-b418-xxxxxxxxxxxxx": failed to dial 22: dial tcp4 127.0.0.1:22: connect: connection refused
9:11PM ERR Fail create ssh connection: ssh: handshake failed: EOF
9:11PM ERR End with error: ssh: handshake failed: EOF

win11 powershell ktctl 0.1.0

**Comment by linfan** [comment]
could you execute command `kubectl cluster-info`, and show the output ?

please MASK your sensitive information with PLACEHOLDER TEXT.
请注意将输出的IP地址等敏感信息替换为占位符

**Comment by Coll-sy** [comment]
> could you execute command `kubectl cluster-info`, and show the output ?
> 
> please MASK your sensitive information with PLACEHOLDER TEXT.
> 请注意将输出的IP地址等敏感信息替换为占位符

PS C:\Users\xxxx> kubectl cluster-info
Kubernetes control plane is running at https://172.22.x.xx:6443
KubeDNS is running at https://172.22.x.xx:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

**Comment by Coll-sy** [comment]
ktctl 0.1.0 downgrade version to 0.0.12 success

D:\Code\IdeaProjects\xxxx>ktctl -d connect --method socks5
?[90m3:04PM?[0m ?[32mINF?[0m Connect Start At 20948
?[90m3:04PM?[0m ?[32mINF?[0m Client address xx.xx.xx.xx
?[90m3:04PM?[0m ?[32mINF?[0m deploy shadow deployment kt-connect-daemon-xoihd in namespace default

?[90m3:04PM?[0m ?[32mINF?[0m pod label: kt=kt-connect-daemon-xoihd
?[90m3:04PM?[0m ?[32mINF?[0m pod: kt-connect-daemon-xoihd-xxxxxxxxxxx-rvqnh is running,but not ready
?[90m3:04PM?[0m ?[32mINF?[0m pod: kt-connect-daemon-xoihd-xxxxxxxxxxx-rvqnh is running,but not ready
?[90m3:04PM?[0m ?[32mINF?[0m pod: kt-connect-daemon-xoihd-xxxxxxxxxxx-rvqnh is running,but not ready
?[90m3:04PM?[0m ?[32mINF?[0m Shadow pod: kt-connect-daemon-xoihd-xxxxxxxxxxx-rvqnh is ready.
?[90m3:04PM?[0m ?[33mDBG?[0m Child, os.Args = [ktctl -d connect --method socks5]
?[90m3:04PM?[0m ?[33mDBG?[0m Child, cmd.Args = [kubectl --kubeconfig=C:\Users\xxxx\.kube\config -n default port-forward kt-connect-daemon-xoihd-xxxxxxxxxxx-rvqnh 2222:22]
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
?[90m3:04PM?[0m ?[32mINF?[0m port-forward start at pid: 10224
?[90m3:04PM?[0m ?[32mINF?[0m ==============================================================
?[90m3:04PM?[0m ?[32mINF?[0m Start SOCKS5 Proxy: export http_proxy=socks5://127.0.0.1:2223
?[90m3:04PM?[0m ?[32mINF?[0m ==============================================================
?[90m3:04PM?[0m ?[33mDBG?[0m Child, os.Args = [ktctl -d connect --method socks5]
?[90m3:04PM?[0m ?[33mDBG?[0m Child, cmd.Args = [ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i C:\Users\xxx/.kt_id_rsa -D 2223 root@127.0.0.1 -p2222 sh loop.sh]
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
?[90m3:04PM?[0m ?[32mINF?[0m vpn(ssh) start at pid: 15956
?[90m3:04PM?[0m ?[32mINF?[0m KT proxy start successful
