### ISSUE TITLE
ERR End with error: port-forward not ready

### ISSUE THREAD

**Issue by gaojianwei421** [alibaba/kt-connect#239]
$ sudo ktctl --waitTime 20 connect
11:14AM INF KtConnect start at 17050
11:14AM INF Private Key generated
11:14AM INF Public key generated
11:14AM INF Successful create ssh config map kt-connect-public-key-xvuo
11:14AM INF Client address 192.168.7.232
11:14AM INF Shadow template is prepare ready.
11:14AM INF Deploy shadow deployment kt-connect-daemon-xvuos in namespace default
11:14AM INF Pod: kt-connect-daemon-xvuos-79d7fd9bfc-wv77h is running, but not ready
11:14AM INF Pod: kt-connect-daemon-xvuos-79d7fd9bfc-wv77h is running, but not ready
11:14AM INF Pod: kt-connect-daemon-xvuos-79d7fd9bfc-wv77h is running, but not ready
11:14AM INF Shadow pod: kt-connect-daemon-xvuos-79d7fd9bfc-wv77h is ready.
11:14AM INF Scan proxy CIDR in namespace scope
11:15AM ERR End with error: port-forward not ready
11:15AM INF Cleaning workspace
11:15AM INF Removing pid /Users/gaojianwei/.ktctl/connect-17050.pid
11:15AM INF Cleaning shadow kt-connect-daemon-xvuos
11:15AM INF Cleaning sshcm kt-connect-public-key-xvuo

**Environment:**
OS：MAC

$ ktctl -v
KT Connect version 0.1.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Log**
添加-d 后 pod无法启动
pod log：
API server listening at: [::]:2345
could not launch process: could not open debug info

**Comment by gaojianwei421** [comment]
手动connect 正常
```
$ kubectl get pods -o wide | grep troubleshoot         
troubleshoot                      2/2     Running   0          42h    172.17.3.19   node003   <none>           <none>

$ kubectl port-forward pod/troubleshoot 2222:22
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
Handling connection for 2222
Handling connection for 2222

```

**Comment by linfan** [comment]
用 `sudo ktctl --debug connect` 运行一下看下具体报错是什么呢？
同时麻烦打印一下 `kubectl cluster-info` 的输出（可以将IP地址等敏感信息替换掉）

**Comment by gaojianwei421** [comment]
加上--debug 后pod的无法启动
pod log：
API server listening at: [::]:2345
could not launch process: could not open debug info

$ sudo ktctl --debug connect
```
Password:
1:45PM INF KtConnect start at 17910
1:45PM INF Private Key generated
1:45PM INF Public key generated
1:45PM INF Successful create ssh config map kt-connect-public-key-ttdv
1:45PM INF Client address 192.168.7.232
1:45PM DBG Create shadow with debug mode
1:45PM INF Shadow template is prepare ready.
1:45PM INF Deploy shadow deployment kt-connect-daemon-ttdvg in namespace default
1:45PM INF Shadow pods not ready ...
1:45PM INF Pod: kt-connect-daemon-ttdvg-78565c6c9f-rm58n is running, but not ready
1:45PM INF Pod: kt-connect-daemon-ttdvg-78565c6c9f-rm58n is running, but not ready
1:45PM INF Shadow pod: kt-connect-daemon-ttdvg-78565c6c9f-rm58n is ready.
1:45PM INF Scan proxy CIDR in namespace scope
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 0
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 1
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 2
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 3
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 4
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 5
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 6
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 7
1:45PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 8
1:46PM DBG Connect to port-forward failed, error: dial tcp :2222: connect: connection refused, retry: 9
1:46PM ERR End with error: port-forward not ready
1:46PM INF Cleaning workspace
1:46PM INF Removing pid /Users/gaojianwei/.ktctl/connect-17910.pid
1:46PM INF Cleaning shadow kt-connect-daemon-ttdvg
1:46PM INF Cleaning sshcm kt-connect-public-key-ttdv
```

$ kubectl cluster-info
```
Kubernetes control plane is running at https://xxxx.com:6443
KubeDNS is running at https://xxxx.com:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by linfan** [comment]
这个问题的根本原因是v0.1.0版本去除了对本地kubectl工具的依赖，改用k8s原生API来实现port-forward功能，但目前的实现在某些情况下依然不够好。目前已修复了一种与Kubernetes control plane地址有关的错误，但从这个issue来看，应该还有其他我们未复现出来的异常情况。下个版本计划将先增加参数选择是否使用本地kubectl工具的port-forward来临时解决这个问题。

**Comment by gaojianwei421** [comment]
感谢您的解答，期待后续的版本。
