### ISSUE TITLE
Error happen when forward remote request to local ssh: handshake failed: EOF

### ISSUE THREAD

**Issue by whhpc19891120** [alibaba/kt-connect#240]
C:\Users\hanpc>ktctl --debug --namespace=kecloud-pmm exchange modules-task-deployment --expose 20090
12:12PM INF KtConnect start at 3568
12:12PM INF Private Key generated
12:12PM INF Public key generated
12:12PM INF Successful create ssh config map kt-exchange-public-key-lsef
12:12PM INF Client address 10.60.1.48
12:12PM DBG Create shadow with debug mode
12:12PM INF Shadow template is prepare ready.
12:12PM INF Deploy shadow deployment modules-task-deployment-kt-vupae in namespace kecloud-pmm
12:13PM INF Pod: modules-task-deployment-kt-vupae-76f45d977-cjm9m is running, but not ready
12:13PM INF Shadow pod: modules-task-deployment-kt-vupae-76f45d977-cjm9m is ready.
12:13PM INF Create exchange shadow modules-task-deployment-kt-vupae in namespace kecloud-pmm
12:13PM INF Scaling deployment modules-task-deployment to 0
12:13PM INF  * modules-task-deployment (0 replicas) success
12:13PM INF Creating shadow inbound(remote->local)
12:13PM INF Remote 10.244.1.94 forward to local 20090
12:13PM DBG Request port forward to https://10.202.61.102:6443
Forwarding from 127.0.0.1:2294 -> 22
Forwarding from [::1]:2294 -> 22
Handling connection for 2294
12:13PM INF Port forward connection established
12:13PM INF ExposeLocalPortsToRemote request from pod:20090 to 127.0.0.1:20090
Handling connection for 2294
E0823 12:13:01.592748    3568 portforward.go:400] an error occurred forwarding 2294 -> 22: error forwarding port 22 to pod 23086bd2e2ae535161c88d3eeadf7e731cc348a2df8b2ffa17ecf99e836cf9a1, uid : exit status 1: 2021/08/23 12:13:01 socat[13228] E connect(5, AF=2 127.0.0.1:22, 16): Connection refused
E0823 12:13:01.593935    3568 portforward.go:400] an error occurred forwarding 2294 -> 22: error forwarding port 22 to pod 23086bd2e2ae535161c88d3eeadf7e731cc348a2df8b2ffa17ecf99e836cf9a1, uid : exit status 1: 2021/08/23 12:13:01 socat[13229] E connect(5, AF=2 127.0.0.1:22, 16): Connection refused
12:13PM ERR Fail create ssh connection: ssh: handshake failed: EOF
12:13PM ERR Fail to create ssh tunnel: ssh: handshake failed: EOF
12:13PM ERR Error happen when forward remote request to local ssh: handshake failed: EOF
12:13PM INF ExposeLocalPortsToRemote request from pod:20090 to 127.0.0.1:20090 finished

**Comment by linfan** [comment]
无法复现，可先尝试升级至 v0.3.0 或更高版本

**Comment by whhpc19891120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好邮件已收到~查阅后会尽快回复~O(∩_∩)O谢谢~

**Comment by fww80** [comment]
是否镜像内部要开启22号端口呢？我也遇到这个问题。

**Comment by fww80** [comment]
11:17AM INF KtConnect 0.3.1 start at 26220 (windows)
11:17AM DBG Private Key generated
11:17AM DBG Public key generated
11:17AM INF Successful create config map kt-connect-shadow-gznkj
11:17AM INF Deploying shadow pod kt-connect-shadow-gznkj in namespace default
11:17AM INF Waiting for pod kt-connect-shadow-gznkj ...
11:17AM INF Pod kt-connect-shadow-gznkj is ready
11:17AM DBG Execute command [nslookup -vc kubernetes.default.svc] in kt-connect-shadow-gznkj:standalone
11:17AM DBG Active DNS
11:17AM WRN Pod route not ready yet,
11:17AM DBG Using port 33108
11:17AM DBG Request port forward pod:22 -> local:33108 via https://7.186.141.103:5443
Forwarding from 127.0.0.1:33108 -> 22
Forwarding from [::1]:33108 -> 22
Handling connection for 33108
11:17AM INF Port forward connection established
Handling connection for 33108
E0304 11:17:32.815340   26220 portforward.go:400] an error occurred forwarding 33108 -> 22: error forwarding port 22 to pod 2f356eec2a5d22f196992d1ead7d16c7053ee0983722c97a0d853f010742e4c6, uid : exit status 1: 2022/03/04 11:17:32 socat[196691] E connect(5, AF=2 127.0.0.1:22, 16): Connection refused
E0304 11:17:32.816731   26220 portforward.go:400] an error occurred forwarding 33108 -> 22: error forwarding port 22 to pod 2f356eec2a5d22f196992d1ead7d16c7053ee0983722c97a0d853f010742e4c6, uid : exit status 1: 2022/03/04 11:17:32 socat[196692] E connect(5, AF=2 127.0.0.1:22, 16): Connection refused
11:17AM ERR Fail create ssh connection error="ssh: handshake failed: EOF"
11:17AM ERR Failed to start error="ssh: handshake failed: EOF"
11:17AM DBG Cleaning workspace
11:17AM INF Removed pid file C:\Users\fwx5323166/.ktctl/connect-26220.pid
11:17AM DBG Received event "C:\\Users\\fwx5323166\\.ktctl\\connect-26220.pid": REMOVE
11:17AM INF Pid file was removed
11:17AM INF Removed key file C:\Users\fwx5323166/.ktctl/pk/kt-connect-shadow-gznkj_id_rsa
11:17AM DBG Dropping hosts records ...
11:17AM INF Cleaning configmap kt-connect-shadow-gznkj
11:17AM INF Cleaning shadow pod kt-connect-shadow-gznkj

**Comment by whhpc19891120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好邮件已收到~查阅后会尽快回复~O(∩_∩)O谢谢~

**Comment by linfan** [comment]
已确认 handshake failed: EOF 错误是由于集群节点未安装 socat 组件所致，已添加到文档的常见问题中
https://alibaba.github.io/kt-connect/#/zh-cn/reference/faq

**Comment by whhpc19891120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好邮件已收到~查阅后会尽快回复~O(∩_∩)O谢谢~
