### ISSUE TITLE
windows 无法连接集群

### ISSUE THREAD

**Issue by xrwang8** [alibaba/kt-connect#241]
![image](https://user-images.githubusercontent.com/68765051/130561532-c73c515a-3261-4839-b0e3-08a97a533c88.png)

**Comment by HAND-zhaiguowen** [comment]
我也是

**Comment by ilaotan** [comment]
改配置文件, 改成master的ip+6443.

**Comment by linfan** [comment]
本地用户目录下的 `.kube\config` 文件里配置的域名无法解析，更换为IP或者有效域名即可
