### ISSUE TITLE
jvm inject 插件无效，没有自动查找 jvmrc 文件

### ISSUE THREAD

**Issue by sg6303** [alibaba/kt-connect#244]
idea 使用 jvm inject 插件，貌似没有自动去找 .jvmrc 文件装载到启动的参数。

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: windows 10
 - Kubernetes 1.20.0
 - KT Version 0.1.0

**Additional context**

**Comment by linfan** [comment]
v0.3.0 及之后版本不再需要使用 jvmrc 插件了
