### ISSUE TITLE
ktctl clean的时候，希望将kt-connect-public-key这类的configMap也一并清理

### ISSUE THREAD

**Issue by muyu66** [alibaba/kt-connect#245]
ktctl clean的时候，希望将kt-connect-public-key这类的configMap也一并清理

![1630985647(1)](https://user-images.githubusercontent.com/20837526/132280273-b21f495e-f271-4c0c-928c-008e7a0232fc.png)

**Comment by linfan** [comment]
clean命令已经支持自动清理ConfigMap了，但只能清理 0.1.1 及以后版本 ktctl 创建的ConfigMap对象（见[版本说明](https://alibaba.github.io/kt-connect/#/zh-cn/changelog)），可以先手工删除这些历史遗留的ConfigMap，然后将本地 ktctl 版本升级即可（当前最新版本为 0.1.2 ）
