### ISSUE TITLE
docker.io/istio/proxyv2:1.6.8   Pull Rate Limit

### ISSUE THREAD

**Issue by zhuzhe1992** [alibaba/kt-connect#248]
**Describe the bug**
每次connect都会创建kt-connect-daemon，这个pod中的docker.io/istio/proxyv2:1.6.8镜像拉取策略是always，6小时很容易超过200次，就会报Pull Rate Limit，connect失败，请说明在哪里改掉这个镜像的拉取策略

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by xyz-li** [comment]
https://medium.com/@kenneth.skertchly/fix-docker-pull-rate-limit-issues-in-istio-sidecars-9f7a410acefd

/close
