### ISSUE TITLE
windows环境下是否支持微服务调试

### ISSUE THREAD

**Issue by Daose1997** [alibaba/kt-connect#256]
在windows环境下，是否支持调试微服务，本地启动服务调用方，通过dubbo协议能否连接到集群内部的服务提供者，如果能的话应该怎么启动ktconnect

**Comment by Daose1997** [comment]
目前已经进行过的尝试有，connect连接集群，可以http调用服务提供者的ip与接口，但是通过注册中心获取到提供者的pod ip之后无法连接，导致无法调用远程服务。同时使用connect与service与此相同，是否暂不支持dubbo协议的代理呢。

**Comment by fanjiwang1992** [comment]
验证了是支持啊

**Comment by fanjiwang1992** [comment]
#247 可以参考一下这个issues,具体错误日志可以发一下

**Comment by Daose1997** [comment]
> #247 可以参考一下这个issues,具体错误日志可以发一下

之前已经参考这个issues解决了，当时看到这个issues之后意识到了是因为dubbo使用NIO的问题，解决后忘记关闭issues了。
