### ISSUE TITLE
exchange的关闭流程中，能够等待集群中的原deployment恢复

### ISSUE THREAD

**Issue by lisirrx** [alibaba/kt-connect#257]
**Is your feature request related to a problem? Please describe.**
在exchange服务的时候，如果客户端ctrl+c停止ktctl，那么没有等待原始的deployment启动完成就断开了exchange
由于恢复origin deployment需要一定时间，比如是一个需要启动1min的应用，这1min内，对该应用的调用不可用

另外希望能加入：
1. 能够设置超时时间
2. 在等待过程中，如果还发送SIGINT信号，能终止等待，直接清理kt相关的pod和deployment

**Describe the solution you'd like**
在 pkg/kt/command/util.go:103附近 CleanupWorkspace 方法中，kubernetes.ScaleTo之后，轮询等待origin deployment的pod启动完成；

**Comment by linfan** [comment]
1. 可使用参数 --recoverWaitTime 设置超时时间，默认120秒，已包含在 v0.2.2 版本
2. 在等待过程中的SIGINT信号处理已合入主干，预计将包含在 v0.2.3 版本
