### ISSUE TITLE
error upgrading connection: pod kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 does not have a host assigned

### ISSUE THREAD

**Issue by hr3685930** [alibaba/kt-connect#258]
**Describe the bug**
ktctl connect 突然连不上,在这之前他是好的

**Log**

8:15PM INF Connect Start At 3919
8:15PM INF Client address 192.168.23.46
8:15PM INF deploy shadow deployment kt-connect-daemon-jsfcp in namespace default

8:15PM INF pod label: kt=kt-connect-daemon-jsfcp
8:15PM INF pod: kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 is running,but not ready
8:15PM INF pod: kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 is running,but not ready
8:15PM INF pod: kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 is running,but not ready
8:15PM INF pod: kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 is running,but not ready
8:15PM INF Shadow pod: kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 is ready.
8:15PM INF Fail to get pod cidr from node.Spec.PODCIDR, try to get with pod sample
8:15PM DBG Child, os.Args = [ktctl --debug connect]
8:15PM DBG Child, cmd.Args = [kubectl --kubeconfig=/Users/herui/.kube/config -n default port-forward kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 2222:22]
error: error upgrading connection: pod kt-connect-daemon-jsfcp-6597cc6f64-4jgv8 does not have a host assigned
8:16PM INF port-forward start at pid: 3920
8:16PM INF port-forward finished
8:16PM DBG Child, os.Args = [ktctl --debug connect]
8:16PM DBG Child, cmd.Args = [sshuttle --dns --to-ns 192.168.0.99 -v -e ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /Users/xxx/.kt_id_rsa -r root@127.0.0.1:2222 -x 127.0.0.1 192.168.0.0/16 172.21.0.0/16]
Starting sshuttle proxy (version 1.0.5).
fw: Starting firewall with Python version 3.9.6
fw: ready method name pf.
c : IPv6 enabled: Using default IPv6 listen address ::1
c : Method: pf
c : IPv4: on
c : IPv6: on
c : UDP : off (not available with pf method)
c : DNS : on
c : User: off (not available with pf method)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '192.168.0.0', 16, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '172.21.0.0', 16, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '127.0.0.1', 32, 0, 0)
c :   (<AddressFamily.AF_INET6: 30>, '::1', 128, 0, 0)
c : DNS requests normally directed at these servers will be redirected to remote:
c :   (<AddressFamily.AF_INET: 2>, '192.168.50.1')
c : TCP redirector listening on ('::1', 12300, 0, 0).
c : TCP redirector listening on ('127.0.0.1', 12300).
c : DNS listening on ('::1', 12299, 0, 0).
c : DNS listening on ('127.0.0.1', 12299).
c : Starting client with Python version 3.9.6
c : Connecting to server...
ssh: connect to host 127.0.0.1 port 2222: Connection refused
c : fatal: c : failed to establish ssh session (1)
8:16PM INF vpn(sshuttle) start at pid: 3921
8:16PM INF KT proxy start successful
8:16PM INF vpn(sshuttle) finished

**Environment:**
 - OS: mac
 - Kubernetes v1.18.8-aliyun.1
 - KT Version kt-0.0.12

**Comment by hr3685930** [comment]
> 看起来是端口转发失败了，先试一下升级到最新`0.2.0`版本看看呢？

 我使用了0.2.0版本，但一直处于Waiting

10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...
10:58PM INF Waiting for shadow pod kt-connect-daemon-iuqmr ...


并且出现了以下错误

SDK.ServerError ErrorCode: InvalidParameter Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidParameter&source=PopGw RequestId: B1BC7445-B717-5BBC-B288-4BA6D92DABCD Message: The specified parameter Container:SecurityContext:CapabilityAdds:AUDIT_WRITE is not valid

**Comment by xyz-li** [comment]
运行ktctl之后， 你看一下 pod的状态详情。 
看样子是 SecurityContext的问题。

**Comment by linfan** [comment]
暂无更多信息且无法复现，Issue先关闭
