### ISSUE TITLE
希望新增一个--context参数

### ISSUE THREAD

**Issue by neo-shirley** [alibaba/kt-connect#261]
大神，提个小小的需求哈~   就是我们生产和测试是两套不同的云服务器网段，所以我们是搞了两套k8s环境，然后本地开发是一个.kube/config文件里面2个context，所以就希望大神能新增一个参数，比如--context自主设置走那套环境。     现在我们每次得自己先手动切context，再启动ktctl~

**Comment by linfan** [comment]
已在v0.2.1版本中增加 --context 全局参数，用于切换 kubeconfig 中的上下文
