### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by beyonderyue** [alibaba/kt-connect#264]
**Describe the bug**
部署咱们的tomcat demo程序
然后执行ktctl connect成功后，
执行 curl tomcat.default:8080
有时候返回 kt-connect demo v1
有时候返回 curl: (52) Empty reply from server

**Log**
c : Accept TCP: 192.168.31.19:50781 -> 10.105.214.120:8080.
c : SW'unknown':Mux#1: deleting (17 remain)
c : SW#-1:192.168.31.19:50408: deleting (16 remain)
c : SW'unknown':Mux#2: deleting (15 remain)
c : SW#-1:192.168.31.19:50414: deleting (14 remain)
c : SW'unknown':Mux#3: deleting (13 remain)
c : SW#-1:192.168.31.19:50415: deleting (12 remain)
c : SW'unknown':Mux#4: deleting (11 remain)
c : SW#-1:192.168.31.19:50416: deleting (10 remain)
c : SW'unknown':Mux#5: deleting (9 remain)
c : SW#-1:192.168.31.19:50419: deleting (8 remain)
c : SW'unknown':Mux#6: deleting (7 remain)
c : SW#-1:192.168.31.19:50438: deleting (6 remain)
c : SW'unknown':Mux#7: deleting (5 remain)
c : SW#-1:192.168.31.19:50449: deleting (4 remain)
 s: SW#7:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50783 -> 10.105.214.120:8080.
c : Accept TCP: 192.168.31.19:50786 -> 10.105.214.120:8080.
c : Accept TCP: 192.168.31.19:50793 -> 10.105.214.120:8080.
 s: SW#11:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50800 -> 10.105.214.120:8080.
 s: SW#12:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50801 -> 10.105.214.120:8080.
c : Accept TCP: 192.168.31.19:50802 -> 10.105.214.120:8080.
 s: SW#14:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50803 -> 10.105.214.120:8080.
c : Accept TCP: 192.168.31.19:50804 -> 10.105.214.120:8080.
 s: SW#16:10.105.214.120:8080: uwrite: got EPIPE
c : warning: closed channel 17 got cmd=TCP_STOP_SENDING len=0
 s: warning: closed channel 17 got cmd=TCP_EOF len=0
c : Accept TCP: 192.168.31.19:50805 -> 10.105.214.120:8080.
 s: SW#17:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50806 -> 10.105.214.120:8080.
 s: SW#-1:10.105.214.120:8080: deleting (27 remain)
 s: SW'unknown':Mux#6: deleting (26 remain)
 s: SW#-1:10.105.214.120:8080: deleting (25 remain)
 s: SW'unknown':Mux#7: deleting (24 remain)
 s: SW#-1:10.105.214.120:8080: deleting (23 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#8: deleting (22 remain)
 s: SW#-1:10.105.214.120:8080: deleting (21 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#9: deleting (20 remain)
 s: SW#-1:10.105.214.120:8080: deleting (19 remain)
 s: SW'unknown':Mux#10: deleting (18 remain)
 s: SW#-1:10.105.214.120:8080: deleting (17 remain)
 s: SW'unknown':Mux#11: deleting (16 remain)
 s: SW#-1:10.105.214.120:8080: deleting (15 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#12: deleting (14 remain)
 s: SW#-1:10.105.214.120:8080: deleting (13 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#13: deleting (12 remain)
 s: SW#-1:10.105.214.120:8080: deleting (11 remain)
 s: SW'unknown':Mux#14: deleting (10 remain)
 s: SW#-1:10.105.214.120:8080: deleting (9 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#15: deleting (8 remain)
 s: SW#-1:10.105.214.120:8080: deleting (7 remain)
 s: SW'unknown':Mux#16: deleting (6 remain)
 s: SW#-1:10.105.214.120:8080: deleting (5 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#17: deleting (4 remain)
 s: SW#-1:10.105.214.120:8080: deleting (3 remain)
 s: SW#-1:10.105.214.120:8080: error was: [Errno 111] Connection refused
 s: SW'unknown':Mux#18: deleting (2 remain)
 s: SW#18:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50811 -> 10.105.214.120:8080.
c : Accept TCP: 192.168.31.19:50814 -> 10.105.214.120:8080.
 s: SW#5:10.105.214.120:8080: uwrite: got EPIPE
c : Accept TCP: 192.168.31.19:50815 -> 10.105.214.120:8080.
 s: warning: closed channel 22 got cmd=TCP_DATA len=83
Handling connection for 2222
8:43PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:43:46
8:44PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:44:16
Handling connection for 2222
8:44PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:44:46
Handling connection for 2222
8:45PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:45:16
Handling connection for 2222
Handling connection for 2222
8:45PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:45:46
8:46PM DBG Heartbeat configmap kt-connect-public-key-garl ticked at 2021-12-05 20:46:12
8:46PM DBG Heartbeat deployment kt-connect-daemon-jyrea ticked at 2021-12-05 20:46:12
8:46PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:46:16
Handling connection for 2222
Handling connection for 2222
8:46PM DBG Heartbeat port forward 2222 ticked at 2021-12-05 20:46:46

**Environment (please complete the following information):**
 - OS: [Mac OS 12.0.1]
 - Kubernetes [1.22.4]
 - KT Version [0.2.2]

**Additional context**

**Comment by linfan** [comment]
疑似是sshuttle的问题，建议试一下 v0.3.0 版本
