### ISSUE TITLE
Doc partially wrong

### ISSUE THREAD

**Issue by cmazxiaoma** [alibaba/kt-connect#268]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26736167/148757296-6429f922-97fa-45ba-8619-ce3555160e54.png)
wrong here

**solution**

kubectl -n mesh-demo apply -f tomcat7-istio.yaml

**Comment by linfan** [comment]
收到~
这种已经有解决方法的问题可以直接提PR哈，提Issue我们还是得手工改 : P

**Comment by cmazxiaoma** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by linfan** [comment]
已修复
