### ISSUE TITLE
如果KUBECONFIG环境变量修改了会报错

### ISSUE THREAD

**Issue by bboysoulcn** [alibaba/kt-connect#270]
**Describe the bug**
export KUBECONFIG=/Users/bboysoul/.kube/develop:/Users/bboysoul/.kube/master:/Users/bboysoul/.kube/nuc:/Users/bboysoul/.kube/k3s

**Log**
➜  ~ ktctl connect       
5:40PM ERR Failed to start error="open /Users/bboysoul/.kube/develop:/Users/bboysoul/.kube/master:/Users/bboysoul/.kube/nuc:/Users/bboysoul/.kube/k3s: no such file or directory"
5:40PM INF Workspace already cleaned

**Comment by linfan** [comment]
收到，应该是对`KUBECONFIG`多路径支持有问题

**Comment by bboysoulcn** [comment]
> 收到，应该是对`KUBECONFIG`多路径支持有问题

没错

**Comment by linfan** [comment]
在v0.3.0版本漏了，预计会在最近的下一个版本中修复

**Comment by bboysoulcn** [comment]
> 在v0.3.0版本漏了，预计会在最近的下一个版本中修复

1
