### ISSUE TITLE
Exchange连接偶发断连

### ISSUE THREAD

**Issue by linfan** [alibaba/kt-connect#271]
**Describe the bug**
SSH反向链接存在偶发断连的情况，考虑增加自动重连逻辑

**Log**
please add -d to debug log
<img width="1152" alt="4391017B-3064-4F5B-BCEE-D2834B5E7838" src="https://user-images.githubusercontent.com/1113435/149704088-f64386bf-b823-4d4f-9ad3-c3297202236e.png">

**Comment by yecaowulei** [comment]
good

**Comment by linfan** [comment]
`0.3.4` 版本已支持 Exchange 自动重连
