### ISSUE TITLE
windows 11的Ubuntu WSL2 环境执行不了sudo ktctl connect

### ISSUE THREAD

**Issue by binze51** [alibaba/kt-connect#275]
**Describe the bug**
我开发环境在windows的Ubuntu子系统里，
下载ktctl_0.3.1_Linux_x86_64.tar.gz后，tar zxf ktctl_0.3.1_Linux_x86_64.tar.gz，sudo mv ktctl /usr/local/bin/ktctl

然后 执行sudo  ktctl connect 报错 panic: runtime error: invalid memory address or nil pointer dereference

**Log**

~$ sudo ktctl connect
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x13bd368]

goroutine 1 [running]:
github.com/alibaba/kt-connect/pkg/kt/command/general.CombineKubeOpts()
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/general/setup.go:45 +0x628
github.com/alibaba/kt-connect/pkg/kt/command.NewConnectCommand.func1(0xc000414580)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/connect.go:27 +0x217
github.com/urfave/cli.HandleAction({0x16ace40, 0xc00041a060}, 0x7)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xa8
github.com/urfave/cli.Command.Run({{0x197c915, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x19b4e36, 0x2d}, {0x199e239, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x652
github.com/urfave/cli.(*App).Run(0xc000322a80, {0xc00013a000, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x80c
main.main()
        /home/runner/work/kt-connect/kt-connect/cmd/ktctl/main.go:46 +0x5d7

**Environment (please complete the following information):**
 - OS: WSL （windows11-Ubuntu20.04）
 - Kubernetes ：1.18.4
 - KT Version ：0.3.1

**Comment by linfan** [comment]
问题收到，在0.3.2版本会尝试修复

**Comment by flypolarbear** [comment]
mac arm64位也有同样的报错

**Comment by linfan** [comment]
刚发现 0.3.2 版本把这个问题漏了，顺延到 0.3.3 ...

**Comment by linfan** [comment]
0.3.3 版本增加了配置有效性的检查，请验证。
如果问题依然出现，麻烦提供一个可复现的 kubeconfg 配置文件，并重新打开这个issue，谢谢
