### ISSUE TITLE
When in k8s the cluster is a non-default namespace and the pod lacks the definition of quota the cluster deploys the additional Webhook that automatically does the intercept check and the ktctl doesn t work

### ISSUE THREAD

**Issue by ismart-yuxi** [alibaba/kt-connect#277]
When in k8s the cluster is a non-default namespace and the pod lacks the definition of quota the cluster deploys the additional Webhook that automatically does the intercept check and the ktctl doesn t work

![FD0BA6D1-3BDF-4e16-8A48-0335084FA843](https://user-images.githubusercontent.com/7867513/156591381-cf01f2eb-c50f-456a-aa89-a7c937d2daf3.png)

**Comment by linfan** [comment]
parameter `--podQuota` will be added in v0.3.2

**Comment by ismart-yuxi** [comment]
thanks!

**Comment by linfan** [comment]
version 0.3.2 released !
