### ISSUE TITLE
window ktctl connect报错

### ISSUE THREAD

**Issue by SeaSharpGit** [alibaba/kt-connect#279]
kt-connect 0.3.1
k8s 1.18.8
<img width="687" alt="截屏2022-03-07 上午10 45 58" src="https://user-images.githubusercontent.com/29559908/156959056-7f81fba3-029f-41e1-8ea5-9efd99882f07.png">
<img width="686" alt="截屏2022-03-07 上午10 47 16" src="https://user-images.githubusercontent.com/29559908/156959176-06c98cf5-769d-41dc-9d83-3110ead41cea.png">

ktctl connect的时候报错
![image](https://user-images.githubusercontent.com/29559908/156959216-4c70c966-743a-44f6-9be8-25d719237137.png)

**Comment by linfan** [comment]
问题已初步定位，预计在0.3.2版本尝试进行修复

**Comment by linfan** [comment]
0.3.2版本已发布，如果问题依然存在，请重新打开此issue
