### ISSUE TITLE
在docker本地docker容器中无法连入kt创建的vpn网络，这个能解决吗

### ISSUE THREAD

**Issue by tttlkkkl** [alibaba/kt-connect#28]
**Is your feature request related to a problem? Please describe.**
由于我们本地开发也都是基于docker镜像进行的，这样做的原因是为了保证每个人手上的PHP运行环境都是统一的，但是在Linux虚拟机中（mac中没有这个问题）docker网络无法连接到VPN网络，即使启用了host网络模式也不行。不知道针对这种情况各位大佬有没有什么解决思路呢。

**Comment by yunlzheng** [comment]
是指在类似在Virtualbox中创建Linux虚拟机，在这个虚机上的docker容器不能连VPN?

**Comment by tttlkkkl** [comment]
是的，就是这种场景。

**Comment by yunlzheng** [comment]
@tttlkkkl 这个我验证一下，然后答复

**Comment by yunlzheng** [comment]
@tttlkkkl 验证了一下，在Ubuntu的虚拟机里面ktctl connect启动以后，如果使用--net=host的话，容器是可以直接通过VPN连接到集群。如果还是有问题，可以在https://github.com/alibaba/kt-connect/blob/master/README.md我放了钉钉的二维码，可以直接在钉钉上联系。
