### ISSUE TITLE
启动后curl报错

### ISSUE THREAD

**Issue by SeaSharpGit** [alibaba/kt-connect#281]
kt-connect 0.3.1
kubectl 1.18.8
window和mac环境一样的效果，启动成功，但是Ping和curl都是不通的
<img width="747" alt="986a85caa93aeeec56332b9801519cc" src="https://user-images.githubusercontent.com/29559908/156973526-c9ce583f-60ef-4fea-9e28-dadab3e24530.png">
![image](https://user-images.githubusercontent.com/29559908/156973710-657bfc4e-de6e-4ed8-b719-0e629112e067.png)
![image](https://user-images.githubusercontent.com/29559908/156973803-b5dccba7-ac6d-402c-a1d0-fe47c731ab62.png)

**Comment by 542928492** [comment]
可以尝试--includeIps参数，把集群的ip段加入。 之前有类似的现象。这么解决的
