### ISSUE TITLE
[Question] Can ktctl resolve the problem about exposing the connection between POD in the k8s

### ISSUE THREAD

**Issue by andyli029** [alibaba/kt-connect#283]

**Comment by andyli029** [comment]
@[linfan](https://github.com/linfan)

**Comment by andyli029** [comment]
@linfan
The process run on the physical node，connect to the pod in the k8s.

**Comment by linfan** [comment]
as long as the physical node has network access to the k8s master (which means you could use kubectl tool connect to that cluster), then kt will works.
