### ISSUE TITLE
使用ktctl connect无法访问kt-dashboard.default.svc.cluster.local之外的地址

### ISSUE THREAD

**Issue by dlhf** [alibaba/kt-connect#29]
为啥我是用了ktctl只能访问这一个 http://kt-dashboard.default.svc.cluster.local 地址，不管是使用ktctl -n jenkins connect，ktctl -n repo-nexus connect,这个kt-dashboard地址都可以访问，但是jenkins命名空间下的http://jenkins.jenkins.svc.cluster.local:8080就是无法访问，repo-nexus下的http://repo-nexus.repo-nexus.svc.cluster.local:8081也无法访问到

**Log**
please add -d to debug log

**Environment**
 - OS: [Centos7.5]
Centos7.5
 - Kubernetes [1.15.3]
 - KT Version [0.0.4]
**Additional context**

**Comment by yunlzheng** [comment]
麻烦验证一下直接访问clusterIP是否通

**Comment by dlhf** [comment]
额，我通过ingress都是可以直接访问的
