### ISSUE TITLE
Win10 ktctl connect 内存占用持续升高

### ISSUE THREAD

**Issue by wdkang123** [alibaba/kt-connect#291]
**Describe the bug**
cmd下 0.3.1 版本: ktctl connect 内存飙升 开了半个小时 已经飙到10GB了 CPU占用高

**Log**
控制台疯狂跑日志
看起来是我本地的问题？一直在往239.255.255.250这个地址做映射？所以导致的内存飙升？
·····
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56003 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60061 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56007 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60060 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56032 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56027 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56012 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60060 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60060 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56036 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60060 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56016 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56020 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60060 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56039 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56045 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56022 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56052 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56030 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56026 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56049 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60064 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56034 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56057 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56061 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56038 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56064 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60069 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60069 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56042 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60068 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56069 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:60069 --> [ff02::c]:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:60065 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] 10.42.0.0:56072 --> 239.255.255.250:3702"
time="2022-03-19T11:22:40+08:00" level=info msg="[UDP] [fe80::4c81:5286:27af:a869]:56044 --> [ff02::c]:3702"
······

**Environment (please complete the following information):**
 - OS: 
 Win10
 - Kubernetes (kubectl version)
 Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
 - KT Version [e.g. 0.0.4]

**Additional context**
在MacBookProM1上运行正常 但是在win10下x86_64的会有飙升的问题
试了公司几台电脑 都会持续升高

感谢!

**Comment by linfan** [comment]
一个已知的Windows系统下运行问题，我们自己使用的时候没有遇到过，但已经有不少社区用户反馈了。
目前已经初步定位原因，会在0.3.2版本上一个修复方案。

**Comment by wdkang123** [comment]
> 
感谢！

**Comment by linfan** [comment]
0.3.2版本已修复

**Comment by qifengz** [comment]
win10下0.3.6版本内存占用很高
![image](https://user-images.githubusercontent.com/42262425/194813499-e5c8b990-bf59-4fd1-ba0b-baf98a5581bd.png)

**Comment by wuyuweixin** [comment]
0.3.7 启动的时候 cpu 飙升
