### ISSUE TITLE
[BUG]超时会导致异常关闭，进而未能做gracefully shutdown

### ISSUE THREAD

**Issue by aak1247** [alibaba/kt-connect#292]
**问题场景**

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: Win10
 - Kubernetes 
 - KT Version 0.3.1 

Error Log:
.......
goroutine 52756 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x19ce982e3b8, 0x72)
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0x6, 0xc0546f7e18, 0x0)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_poll_runtime.go:
84 +0x32
internal/poll.execIO(0xc0562a1b98, 0x19134d8)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_windows.go:175 +
0xe5
internal/poll.(*FD).Read(0xc0562a1b80, {0xc055c2d0b6, 0x1, 0x1})
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_windows.go:441 +
0x25f
net.(*netFD).Read(0xc0562a1b80, {0xc055c2d0b6, 0x19cbbf60108, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc04c052968, {0xc055c2d0b6, 0x157cf00, 0x1})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/net.go:183 +0x45
github.com/wzshiming/socks5.(*Server).handleAssociate.func1()
        /home/runner/go/pkg/mod/github.com/wzshiming/socks5@v0.4.0/server.go:309
...
goroutine 105572 [IO wait]:
internal/poll.runtime_pollWait(0x19ce9282038, 0x72)
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc19756e298, 0x3535322e353532, 0x0)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_poll_runtime.go:
84 +0x32
internal/poll.execIO(0xc19756e298, 0x19134e0)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_windows.go:175 +
0xe5
internal/poll.(*FD).ReadFrom(0xc19756e280, {0xc01e5e6000, 0xc059e08820, 0x203142
0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_windows.go:581 +
0x155
net.(*netFD).readFrom(0xc19756e280, {0xc01e5e6000, 0x0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/fd_posix.go:62 +0x29
net.(*UDPConn).readFrom(0xc226ab8400, {0xc01e5e6000, 0x0, 0x3232323232}, 0xc5082
68b40)
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/udpsock_posix.go:47 +0x3e
net.(*UDPConn).readFromUDP(0xc10a492110, {0xc01e5e6000, 0xc19cac5da8, 0x619c68},
 0xc19756e280)
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/udpsock.go:116 +0x31
net.(*UDPConn).ReadFrom(0xc2f8154d20, {0xc01e5e6000, 0xffff, 0x10000})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/udpsock.go:125 +0x50
github.com/xjasonlyu/tun2socks/v2/proxy.(*socksPacketConn).ReadFrom(0xc3e2f72b70
, {0xc01e5e6000, 0xc19cac5e38, 0x10000})
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220107
082344-761069ebf49b/proxy/socks5.go:157 +0x3a
github.com/xjasonlyu/tun2socks/v2/tunnel/statistic.(*udpTracker).ReadFrom(0xc317
c7a360, {0xc01e5e6000, 0x28128e0, 0x28128e0})
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220107
082344-761069ebf49b/tunnel/statistic/tracker.go:108 +0x2e
github.com/xjasonlyu/tun2socks/v2/tunnel.handleUDPToLocal({0x1acb7e8, 0xc3e7ad44
10}, {0x1acf770, 0xc317c7a360})
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220107
082344-761069ebf49b/tunnel/udp.go:137 +0x182
github.com/xjasonlyu/tun2socks/v2/tunnel.handleUDP.func3.2()
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220107
082344-761069ebf49b/tunnel/udp.go:108 +0x112
created by github.com/xjasonlyu/tun2socks/v2/tunnel.handleUDP.func3
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220107
082344-761069ebf49b/tunnel/udp.go:103 +0x348

**Comment by aak1247** [comment]
带来的影响是，在未正确关闭前，网络还是会受影响

**Comment by linfan** [comment]
今晚发布 0.3.2 版本，从堆栈来看，这个问题在新版本可能已修复

**Comment by linfan** [comment]
Issue先关闭，如果新版本依然有问题请reopen
