### ISSUE TITLE
windows 执行connect完毕后，静态路由未清理

### ISSUE THREAD

**Issue by li-chp** [alibaba/kt-connect#294]
**Describe the bug**
connect完毕后，留下永久理由没有清理

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [windows]
 - Kubernetes [any]
 - KT Version [e.g. 0.3.2]

**Additional context**

**Comment by li-chp** [comment]
route print -4可查看

**Comment by linfan** [comment]
未复现，能具体提供一下route print的输出吗？

**Comment by linfan** [comment]
此处考虑增加一个退出时候主动清除路由配置的逻辑，目前是让系统在删除网卡时候自动清除网卡关联的路由。从现象上看像是某种情况下系统不会做自动清理，导致路由被留在本地路由表上了

**Comment by linfan** [comment]
0.3.3 版本 clean 命令已增加 `--sweepLocalRoute` 参数用于识别并清理由ktctl创建的本地路由规则，请验证。由于目前仅有一例反馈，且我们的开发环境无法复现windows系统退出ktctl connect后依然遗留本地路由的情况，暂时不在退出进程时做额外处理

**Comment by linfan** [comment]
@li-chp 问题已复现，确认在某些Windows环境下会存在路由残留问题。

这个问题会在 0.3.5 版本中彻底解决。

**Comment by linfan** [comment]
`0.3.5` 版本已发布
