### ISSUE TITLE
Windows mesh mode为auto时，报错提示未找到kt.conf

### ISSUE THREAD

**Issue by li-chp** [alibaba/kt-connect#295]
**Describe the bug**

Windows mesh mode为auto时，报错提示未找到kt.conf

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [windows]
 - Kubernetes any]
 - KT Version [0.3.2]

**Additional context**

**Comment by linfan** [comment]
是每次执行都报这个错误，还是偶然出现一次？能提供一下执行时候的完整命令参数吗？（服务名和端口可以脱敏替换掉）

**Comment by li-chp** [comment]
最近试了几次都没有复现，这个bug麻烦关掉吧。
