### ISSUE TITLE
使用 --shareShadow一直等待

### ISSUE THREAD

**Issue by zjline** [alibaba/kt-connect#296]
命令：ktctl connect --shareShadow  --includeIps 172.168.0.0/16
日志：Pod 'kt-connect-shadow-daemon' not finished yet, waiting
有别人正在使用，本机就无法连接嘛

**Comment by linfan** [comment]
`--shareShadow` 的时候会固定使用 kt-connect-shadow-daemon 作为 shadow pod 的名字，所有人共用。

当某个时刻当使用的最后一个人退出了，这个 pod 会被删除，如果正在删除的过程中，正好又有新用户来连，就会提示这个等待信息。如果一直卡在这个地方，先查一下 kt-connect-shadow-daemon  的状态：`kubectl get pod kt-connect-shadow-daemon`

如果Pod始终处于Terminating状态，可能是集群中存在某种Hook影响了Shadow pod删除，可以尝试手工移除Pod的finalizers：
`kubectl patch pod kt-connect-shadow-daemon -p '{"metadata":{"finalizers":null}}'`

**Comment by linfan** [comment]
先关闭了，如果还有问题，可以补充信息再Reopen
