### ISSUE TITLE
用exchange和mesh 不能转发ingress的流量么？

### ISSUE THREAD

**Issue by ystyle** [alibaba/kt-connect#298]
**Describe the bug**
我在本地运行了ktctl connect 和 ktctl exchange。 
然后直接从ingress进去的流量（ingress -> api-gateway > app-service -> pod）不不会转发到本地。
但我直接 在本地通过 service访问是会到本地的
另外在集群里api-gateway的pod直接用curl是能转发到本地的

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: archlinux
 - Kubernetes: v1.21.4+k3s1
 - KT Version:  0.3.2

**Additional context**

**Comment by fosin** [comment]
+1

OS: CentOS7.9
Kubernetes: v1.19.16
KT Version: 0.3.2

**Comment by linfan** [comment]
@ystyle 原理上来说应该可以，kt-connect会修改service的selector，让它指向shadow pod，所以只要流量经过service，就应该被重定向到shadow pod然后到本地。确定流量是经过 app-service 的么？

@fosin 同样的问题，如果对静态资源的访问是不经过目标Service路由的（比如托管在CDN），那么就不会被重定向到本地

**Comment by ystyle** [comment]
@linfan  api-gateway也是跑在集群的， 里边都是难过Service name访问pod的。 测试也是直接用service name测试的。 集群里和本地都可以访问到，但从ingress过去的不能。

**Comment by fosin** [comment]
静态资源文件都是本地得，没有CDN。
另外我发现不经过ingress，即使直接使用nodeport暴漏端口的service访问也会存在问题，时好时坏得，调试好难搞啊。

**Comment by linfan** [comment]
从最后这个日志来看，确实是Exchange连接已经断开了，`0.3.4` 以及之后版本增加了自动重连，应该能修复这个问题。
可以直接升级到最新的 `0.3.5` 版本再试试
