### ISSUE TITLE
0.3.2 版本的自动清理会把其它用户正在使用的kt-connect-shadow pod给删除

### ISSUE THREAD

**Issue by ystyle** [alibaba/kt-connect#299]
**Describe the bug**
0.3.2 版本的自动清理会把其它用户正在使用的kt-connect-shadow pod给删除

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: archlinux , windows 10
 - Kubernetes v1.21.4+k3s1
 - KT Version: 0.3.2

**Additional context**

**Comment by linfan** [comment]
@ystyle 已经在 0.3.3-beta1 版本中修复，
[https://gith](https://github.com/alibaba/kt-connect/releases/tag/v0.3.3-beta1)

**Comment by linfan** [comment]
0.3.3 正式版已发布
