### ISSUE TITLE
0.3.2启动ktctl connect报错

### ISSUE THREAD

**Issue by fosin** [alibaba/kt-connect#300]
**Describe the bug**
0.3.2启动ktctl connect报错，同样条件下使用0.3.1启动就正常。
麻烦看看，谢谢！
![image](https://user-images.githubusercontent.com/32410502/162712427-9c7709f5-2abd-49bf-8bf8-27be00d34764.png)
![image](https://user-images.githubusercontent.com/32410502/162712848-47a6a760-6ab5-4d77-bcc9-2d6bc4320eac.png)

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Kubernetes [e.g. 1.19.16]
 - KT Version [e.g. 0.3.2]

**Additional context**

**Comment by linfan** [comment]
麻烦提供一下带 --debug 参数的日志
```
ktctl --debug connect
```

**Comment by fosin** [comment]
我怀疑是把K8S的控制平面的IP198也纳入路由导致得，使用--excludeIps排除也不行。
![image](https://user-images.githubusercontent.com/32410502/162876475-a5d03fce-88c9-4960-987b-eedd22e7d53c.png)

**Comment by linfan** [comment]
看起来是获取集群Pod IP范围的逻辑有些问题，将控制平面的IP地址也识别成Pod的IP地址范围了，应该在下个版本能修复

**Comment by linfan** [comment]
@fosin 已发布 0.3.3-beta1，针对上述情况做了处理，试试看是否已修复问题？
https://github.com/alibaba/kt-connect/releases/tag/v0.3.3-beta1

**Comment by fosin** [comment]
好的。

**Comment by fosin** [comment]
是可以正常启动了，不过网卡地址还是会注册上172.16.1.198，不确定是否真正解决问题了，因为为了绕开0.3.2的问题，我把k8s的内部IP改成内网IP172.16.1.198了。
![image](https://user-images.githubusercontent.com/32410502/163554981-b2e5d0de-7561-4ebe-a9a9-fcc114758ee3.png)

**Comment by linfan** [comment]
经验证 0.3.3-beta1 的修复方案不完整，依然需要配合 `--excludeIps` 参数才能正常使用。已经发布新的 0.3.3-beta2 版本，这个版本应该彻底解决这个问题了

**Comment by fosin** [comment]
还是没搞定呢，172.16.1.198这个IP还是会出现在虚拟网卡中

C:\WINDOWS\system32>ktctl -d connect
2:36PM INF KtConnect 0.3.3-beta2 start at 16956 (windows amd64)
2:36PM DBG Rectify pod kt-rectifier-nphfr created
2:36PM INF Fetching cluster time ...
2:36PM DBG Execute command [date +%s] in kt-rectifier-nphfr:standalone
2:36PM INF No time difference
2:36PM DBG Find 3 kt pods
2:36PM DBG Private Key generated
2:36PM DBG Public key generated
2:36PM INF Successful create config map kt-connect-shadow-wtesc
2:36PM INF Deploying shadow pod kt-connect-shadow-wtesc in namespace default
2:36PM INF Waiting for pod kt-connect-shadow-wtesc ...
2:36PM INF Pod kt-connect-shadow-wtesc is ready
2:36PM DBG Using port 46210
2:36PM DBG Request port forward pod:22 -> local:46210 via https://100.100.1.198:6443
Forwarding from 127.0.0.1:46210 -> 22
Forwarding from [::1]:46210 -> 22
2:36PM INF Port forward connection established
Handling connection for 46210
Handling connection for 46210
2022/04/22 14:36:20 Using existing driver 0.14
2022/04/22 14:36:20 Creating adapter
time="2022-04-22T14:36:21+08:00" level=info msg="[STACK] tun://KtConnectTunnel <-> socks5://127.0.0.1:2223"
2:36PM INF Tun device KtConnectTunnel is ready
2:36PM DBG Cluster CIDR are: [10.96.0.0/16 10.244.0.0/24 172.16.1.198/32]
2:36PM DBG Using cluster ip 100.100.1.198
2:36PM INF Adding route to 10.96.0.0/16
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ip set address KtConnectTunnel static 10.96.0.0 255.255.0.0]
2:36PM DBG Start netsh.exe at pid: 5876
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ipv4 add route 10.96.0.0/16 KtConnectTunnel 10.96.0.0]
2:36PM DBG Start netsh.exe at pid: 1904
2:36PM INF Adding route to 10.244.0.0/24
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ip add address KtConnectTunnel 10.244.0.0 255.255.255.0]
2:36PM DBG Start netsh.exe at pid: 6480
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ipv4 add route 10.244.0.0/24 KtConnectTunnel 10.244.0.0]
2:36PM DBG Start netsh.exe at pid: 5900
2:36PM INF Adding route to 172.16.1.198/32
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ip add address KtConnectTunnel 172.16.1.198 255.255.255.255]
2:36PM DBG Start netsh.exe at pid: 16564
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ipv4 add route 172.16.1.198/32 KtConnectTunnel 172.16.1.198]
2:36PM DBG Start netsh.exe at pid: 19096
2:36PM INF Route to tun device completed
2:36PM INF Setting up dns in local mode
2:36PM DBG Service found: anan-authserver.default 10.96.75.82
2:36PM DBG Service found: anan-cloudgateway.default 10.96.32.119
2:36PM DBG Service found: anan-exam.default 10.96.191.214
2:36PM DBG Service found: anan-nginx-ingress.default 10.96.130.27
2:36PM DBG Service found: anan-platformserver.default 10.96.175.70
2:36PM DBG Service found: anan-sbaserver.default 10.96.237.228
2:36PM DBG Service found: kubernetes.default 10.96.0.1
2:36PM DBG Service found: minio.default 10.96.106.249
2:36PM DBG Headless service found: minio-headless.default 10.244.0.19
2:36PM DBG Service found: mysql-mgr.default 10.96.159.100
2:36PM DBG Headless service found: mysql-mgr-headless.default 10.244.0.7
2:36PM DBG Service found: rabbitmq.default 10.96.45.218
2:36PM DBG Headless service found: rabbitmq-headless.default 10.244.0.6
2:36PM DBG Service found: redis.default 10.96.186.252
2:36PM DBG Headless service found: redis-headless.default 10.244.0.5
2:36PM DBG Service found: redisinsight.default 10.96.172.4
2:36PM DBG Headless service found: redisinsight-headless.default 10.244.0.14
2:36PM DBG Dump hosts successful
2:36PM DBG Service redis-headless added
2:36PM DBG Service mysql-mgr-headless added
2:36PM DBG Service anan-cloudgateway added
2:36PM DBG Service anan-sbaserver added
2:36PM DBG Service anan-exam added
2:36PM DBG Service redis added
2:36PM DBG Service anan-platformserver added
2:36PM DBG Service anan-nginx-ingress added
2:36PM DBG Service minio-headless added
2:36PM DBG Service anan-authserver added
2:36PM DBG Service redisinsight-headless added
2:36PM DBG Service minio added
2:36PM DBG Service redisinsight added
2:36PM DBG Service kubernetes added
2:36PM DBG Service rabbitmq-headless added
2:36PM DBG Service rabbitmq added
2:36PM DBG Service mysql-mgr added
2:36PM DBG Using port 43397
2:36PM DBG Request port forward pod:53 -> local:43397 via https://100.100.1.198:6443
Forwarding from 127.0.0.1:43397 -> 53
Forwarding from [::1]:43397 -> 53
2:36PM INF Port forward connection established
Handling connection for 43397
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ip show dnsservers]
2:36PM DBG Start netsh.exe at pid: 20832
2:36PM DBG Setup local DNS with shadow pod 127.0.0.1:43397 and upstream 192.168.255.10:53
2:36PM INF Creating udp dns on port 53
2:36PM DBG Task name = netsh.exe, cmd.Args = [netsh interface ip set dnsservers name=KtConnectTunnel source=static address=127.0.0.1]
2:36PM DBG Start netsh.exe at pid: 19428
Handling connection for 43397
2:36PM DBG Found domain www.microsoft.com. (6) in cluster dns (127.0.0.1:43397)
Handling connection for 43397
2:36PM DBG Found domain szlong.weixin.qq.com. (1) in cluster dns (127.0.0.1:43397)
2:36PM DBG Pod kt-connect-shadow-nctts deleted
Handling connection for 43397
2:36PM DBG Found domain mtalk.google.com. (1) in cluster dns (127.0.0.1:43397)
2:36PM INF ---------------------------------------------------------------
2:36PM INF  All looks good, now you can access to resources in the kubernetes cluster
2:36PM INF ---------------------------------------------------------------
Handling connection for 43397
2:36PM DBG Found domain poll.exmail.qq.com. (1) in cluster dns (127.0.0.1:43397)
Handling connection for 43397

**Comment by linfan** [comment]
日志里”Using cluster ip 100.100.1.198“这行显示当前从 kubeconfig 读取到的API Server IP应该是100.100.1.198这个地址。同时由于检查到有Service的Cluster IP是”172.16.1.198“，所以会添加相应的路由记录。

这种情况下，本地kubectl工具应该也是通过100.100.1.198连接集群的，理论上不会影响集群的正常使用。如果确实不希望有这个路由，可以加`--excludeIps`参数排除。

0.3.3 正式版本已发布，issue先关闭，如果依然有相关问题，可以reopen。
