### ISSUE TITLE
能支持下 go install的方式安装ktctl吗? 谢谢

### ISSUE THREAD

**Issue by izouxv** [alibaba/kt-connect#301]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yearnxiao** [comment]
什么脑残需求？

**Comment by izouxv** [comment]
你会说人话吗?  这个需求脑残吗?

**Comment by izouxv** [comment]
<img width="240" alt="Screen Shot 2022-04-15 at 17 17 57" src="https://user-images.githubusercontent.com/1646763/163552590-dc46ec42-4fc7-41f3-8b55-780397de8ce2.png">

**Comment by izouxv** [comment]
这个不是很基本的需求吗?   google那么多app都支持 go install的方式安装.

**Comment by linfan** [comment]
@yearnxiao 请注意用语文明

@izouxv 验证了一下，确实现在 go install 直接拉 kt-connect 会报错，这个我们近期会查一下原因

**Comment by linfan** [comment]
已确认原因是由于`kt-connect`的`go.mod`配置包含一条`replace`记录导致无法直接`go install <Git仓库地址>`安装。

一种绕过方法是先`git clone`代码到本地，然后进入代码库内执行`go install`安装：

```bash
git clone https://github.com/alibaba/kt-connect.git
cd kt-connect/cmd/ktctl
go install
```

参考：
- Golang的[相关模块设计](https://github.com/golang/go/issues/40276)
- StackoverFlow的[相关问题回复](https://stackoverflow.com/a/69807233)

**Comment by izouxv** [comment]
可以在cmd里面内建一个mod. 然后就可以直接 go install github.com/alibaba/kt-connect/cmd/ktctl, 不需要git clone,  附件里面有个例子就不提pr了. .  直接执行就可以 go install github.com/alibaba/kt-connect/cmd/ktctl2 . 试试看. 
[cmd.zip](https://github.com/alibaba/kt-connect/files/8510383/cmd.zip)

**Comment by izouxv** [comment]
@linfan   把cmd替换调. 试试 go install github.com/alibaba/kt-connect/cmd/ktctl2
