### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by bearmr** [alibaba/kt-connect#304]
11:23AM DBG Found domain doh.zjurl.cn. (1) in cluster dns (127.0.0.1:36213)
11:23AM INF ---------------------------------------------------------------
11:23AM INF  All looks good, now you can access to resources in the kubernetes cluster
11:23AM INF ---------------------------------------------------------------
panic: runtime error: slice bounds out of range [:5818] with capacity 1420

goroutine 197 [running]:
github.com/xjasonlyu/tun2socks/v2/core/device/iobased.(*Endpoint).dispatchLoop(0xc00070f000, 0x0?)
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220328035721-6a7d8f6bac52/core/device/iobased/endpoint.go:97 +0x25f
created by github.com/xjasonlyu/tun2socks/v2/core/device/iobased.(*Endpoint).Attach.func1
        /home/runner/go/pkg/mod/github.com/linfan/tun2socks/v2@v2.3.3-0.20220328035721-6a7d8f6bac52/core/device/iobased/endpoint.go:72 +0x98
注册上去了立马断了

**Comment by linfan** [comment]
收到，这个问题在master分支上已修复，预计这两天会发beta包

**Comment by linfan** [comment]
已发布 v0.3.3-beta3
https://github.com/alibaba/kt-connect/releases/tag/v0.3.3-beta3
