### ISSUE TITLE
使用mesh模式，是不是还需要自己复制header

### ISSUE THREAD

**Issue by someorz** [alibaba/kt-connect#306]
在调试微服务时，请求到网关A，然后到调试的服务B，然后再通过feign调用另一个服务C，是不是需要在网关复制mesh指定的header，还有feign调用时也要复制mesh指定的header才可以。

**Comment by linfan** [comment]
是的，当跨服务的时候，如果希望后面的Service还能走到本地，就得让mesh命令时候指定的Header沿着调用一直保持。否则就只能使用exchange，但这样会把所有流量都导向到本地。

**Comment by someorz** [comment]
清楚了，谢谢
