### ISSUE TITLE
ktctl connect error

### ISSUE THREAD

**Issue by luciferhs** [alibaba/kt-connect#308]
我能本地访问到k8s集群，但是执行ktctl connect 报错
```
10:59AM INF KtConnect 0.3.4 start at 127 (linux amd64)
10:59AM INF Fetching cluster time ...
11:00AM ERR Failed to start: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```

**Comment by 542928492** [comment]
我这边也看到出现大量的连接问题，海量的日志滚动输出
C:\Users\enmonster\Downloads\ktctl_0.3.4_Windows_x86_64>ktctl.exe connect -n qa
12:16PM INF Using cluster context kubernetes (kubernetes)
12:16PM INF KtConnect 0.3.4 start at 15980 (windows amd64)
12:16PM INF Fetching cluster time ...
12:16PM INF Successful create config map kt-connect-shadow-qheof
12:16PM INF Deploying shadow pod kt-connect-shadow-qheof in namespace qa
12:16PM INF Waiting for pod kt-connect-shadow-qheof ...
12:16PM INF Pod kt-connect-shadow-qheof is ready
12:16PM INF Port forward local:33503 -> pod kt-connect-shadow-qheof:22 established
12:16PM INF Socks proxy established
2022/05/07 12:16:22 Using existing driver 0.14
2022/05/07 12:16:22 Creating adapter
12:16PM INF Tun device KtConnectTunnel is ready
12:16PM INF Adding route to 172.21.0.0/16
12:16PM INF Adding route to 172.20.0.0/16
12:16PM INF Route to tun device completed
12:16PM INF Setting up dns in local mode
12:16PM INF Port forward local:33290 -> pod kt-connect-shadow-qheof:53 established
12:16PM INF Creating udp dns on port 53
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63108->127.0.0.1:53: i/o timeout"
12:16PM INF ---------------------------------------------------------------
12:16PM INF  All looks good, now you can access to resources in the kubernetes cluster
12:16PM INF ---------------------------------------------------------------
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63109->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63110->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63111->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63112->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63113->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63114->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63115->127.0.0.1:53: i/o timeout"

**Comment by linfan** [comment]
@542928492 你这个问题在`0.3.5`版本已经修复了，在0.3.4有一个Windows DNS解析的BUG

**Comment by linfan** [comment]
@luciferhs 这个问题出在集群节点kubelet与k8s api server通信上，从相关资料来看，可能是由于api server有过版本升级，但未重启节点上的kubelet进程所致，也有可能就是`kube-apiserver-kubelet-client`这个k8s系统用户由于某种原因被从默认的`kubelet-api-admin`权限组移出了。

可以尝试以下修复方法：

1. 登录k8s节点，重启`kubelet`进程：

```
systemctl restart kubelet
```

2. 为kubelet使用的`kube-apiserver-kubelet-client`系统用户重新绑定`kubelet-api-admin`权限组：

创建`kubelet-api-binding.yaml`文件内容如下：

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-api-admin
subjects:
- kind: User
  name: kube-apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
```

然后执行它

```
kubectl apply -f kubelet-api-binding.yaml
```

总之这应该是一个集群本身的问题。

参考：
- https://kb.vmware.com/s/article/84236
- https://stackoverflow.com/questions/54572775/kubectl-logs-f-gets-authorization-error
- https://github.com/tilt-dev/tilt/issues/3547
