### ISSUE TITLE
ktctl connect 异常 0.3.4

### ISSUE THREAD

**Issue by 542928492** [alibaba/kt-connect#309]
**Describe the bug**

到出现大量的连接问题，海量的日志滚动输出
C:\Users\enmonster\Downloads\ktctl_0.3.4_Windows_x86_64>ktctl.exe connect -n qa
12:16PM INF Using cluster context kubernetes (kubernetes)
12:16PM INF KtConnect 0.3.4 start at 15980 (windows amd64)
12:16PM INF Fetching cluster time ...
12:16PM INF Successful create config map kt-connect-shadow-qheof
12:16PM INF Deploying shadow pod kt-connect-shadow-qheof in namespace qa
12:16PM INF Waiting for pod kt-connect-shadow-qheof ...
12:16PM INF Pod kt-connect-shadow-qheof is ready
12:16PM INF Port forward local:33503 -> pod kt-connect-shadow-qheof:22 established
12:16PM INF Socks proxy established
2022/05/07 12:16:22 Using existing driver 0.14
2022/05/07 12:16:22 Creating adapter
12:16PM INF Tun device KtConnectTunnel is ready
12:16PM INF Adding route to 172.21.0.0/16
12:16PM INF Adding route to 172.20.0.0/16
12:16PM INF Route to tun device completed
12:16PM INF Setting up dns in local mode
12:16PM INF Port forward local:33290 -> pod kt-connect-shadow-qheof:53 established
12:16PM INF Creating udp dns on port 53
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63108->127.0.0.1:53: i/o timeout"
12:16PM INF ---------------------------------------------------------------
12:16PM INF  All looks good, now you can access to resources in the kubernetes cluster
12:16PM INF ---------------------------------------------------------------
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63109->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63110->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63111->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63112->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63113->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63114->127.0.0.1:53: i/o timeout"
12:16PM WRN Failed to lookup 1.179.168.192.in-addr.arpa. (1) in upstream dns (:53) error="read udp 127.0.0.1:63115->127.0.0.1:53: i/o timeout"

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by 542928492** [comment]
第一次执行命令运行的时候 是没有异常的。  但是随后关闭再执行 就一直这样。
是本地环境台复杂了吗？  我本地有clash  和 云枢  网络vpn 隧道工具同时在运行

**Comment by linfan** [comment]
0.3.4版本在Windows下的DNS解析有些异常，已经在`0.3.5`版本中修复
