### ISSUE TITLE
kt-connect can't work

### ISSUE THREAD

**Issue by sandshell** [alibaba/kt-connect#31]
**Describe the bug**
when i finish install kt-connect,i can't curl any podIP:port and clusterIP:port in local linux machine.
in local machine 
[root@localhost ~]# ktctl --kubeconfig /root/.kube/admin.conf connect
2019/10/29 22:02:06 Client address 10.0.0.100
2019/10/29 22:02:07 Deploying proxy deployment kt-connect-daemon-hgswr in namespace default
2019/10/29 22:02:07 Pod status is Pending
2019/10/29 22:02:09 Pod status is Pending
2019/10/29 22:02:11 Pod status is Running
2019/10/29 22:02:11 Success deploy proxy deployment kt-connect-daemon-hgswr in namespace default
Daemon Start At 18437

[root@localhost ~]# ps -ef |grep sshuttle
root      18583  18448  0 14:51 pts/1    00:00:00 grep --color=auto sshuttle
[root@localhost ~]# 

**Log**
please add -d to debug log
I can't find any log in /var/log/messages

**Environment (please complete the following information):**
 - OS: [CentOS 7.5]
 - Kubernetes [e.g. 1.15.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by yunlzheng** [comment]
https://github.com/alibaba/kt-connect/releases/tag/kt-0.0.6  这里下载0.0.6版本的包试试

**Comment by yunlzheng** [comment]
另外 connect命令由于调用了sshuttle会要求输入root的密码，日志里面好像没看到相关的操作
