### ISSUE TITLE
exhange和preview不检查expose的端口是否启用

### ISSUE THREAD

**Issue by wuxs** [alibaba/kt-connect#312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by linfan** [comment]
exchange / preview 默认是会检查 expose 的本地端口是否监听已经服务端口是否存在的。
请详细描述一下问题，是希望不要做上述检查？

**Comment by wuxs** [comment]
希望这个端口是否监听可以做成一个可选项

**Comment by linfan** [comment]
感谢你提交的PR 👍 
`0.3.5` 已支持 `--skipPortChecking` 参数，默认为false，即保留端口检查，这个检查能减少许多由于参数误用引起的答疑。
可以通过 ktctl config 命令将该参数设置为默认开启：

```
ktctl config set exchange.skip-port-checking=true
ktctl config set mesh.skip-port-checking=true
ktctl config set preview.skip-port-checking=true
```
