### ISSUE TITLE
将annotation 添加到 container上

### ISSUE THREAD

**Issue by wuxs** [alibaba/kt-connect#313]
能否将annotation添加 container 上，这样就能自动创建 dapr 的 sidecar 了

**Comment by linfan** [comment]
我理解annotation应该只能加到pod上吧，能举一个container包含annotation的例子吗？

**Comment by wuxs** [comment]
不好意思，我记错了。是将annotation添加到 Deployment的 spec.template.metadata 里面
这个是[dapr的例子](https://github.com/dapr/quickstarts/blob/master/tutorials/hello-kubernetes/deploy/python.yaml)

**Comment by linfan** [comment]
感谢示例，跟进得晚了一些，预计在 0.3.6 的第一个 beta 版本里会增加这个配置能力

**Comment by linfan** [comment]
@wuxs Deployment通过 spec.template.metadata 添加的 annotation 实际就是加到 Pod 上的，通过 ktctl 的 `--withAnnotation` 参数可以实现这个效果
