### ISSUE TITLE
windows静态路由删除的逻辑有问题

### ISSUE THREAD

**Issue by li-chp** [alibaba/kt-connect#319]
**Describe the bug**

tun_windows.go
getInterfaceIndex方法，获取要删除的路由，获取index逻辑不对。像我本地的，小于10的都得不到。

idx := strings.SplitN(strings.TrimPrefix(line, " "), " ", 2)[0]

C:\Users\Administrator>netsh interface ipv4 show interfaces

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 58           5       65535  connected     EtConnectTunnel
  8          50        1500  connected     WLAN
  7          25        1500  disconnected  本地连接* 1
 14           5        1500  disconnected  以太网
 19          25        1500  disconnected  本地连接* 2
  3          55        1500  disconnected  以太网 2
  6           1        1400  connected     以太网 3

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [window10]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [v0.3.5]

**Additional context**

**Comment by li-chp** [comment]
试了下，TrimPrefix改成TrimLeft就可以了，这个bug会把本地默认路由删掉。

**Comment by linfan** [comment]
@li-chp 感谢反馈，这个地方确实是一个失误

已处理，会在下个beta版本里发布。类似问题也欢迎直接提交PR哈~~

**Comment by linfan** [comment]
fixed in `v0.3.6`
