### ISSUE TITLE
0.0.6 版本源码编译报错

### ISSUE THREAD

**Issue by sandshell** [alibaba/kt-connect#32]
**Describe the bug**
下载源码包：kt-connect-kt-0.0.6.zip
在Centos 7.5机器编译kt-connect-kt-0.0.6过程中报错如下：
[root@k8s-master-15-81 ~]# go version
go version go1.12.9 linux/amd64
[root@k8s-master-15-81 ~]# 
[root@k8s-master-15-81 tools]# ll
total 1228
drwxr-xr-x 11 root root    4096 Oct 29 09:31 kt-connect-kt-0.0.6
-rw-r--r--  1 root root 1251777 Oct 29 09:20 kt-connect-kt-0.0.6.zip
[root@k8s-master-15-81 tools]# cd kt-connect-kt-0.0.6/
[root@k8s-master-15-81 kt-connect-kt-0.0.6]# ll
total 80
drwxr-xr-x 2 root root  4096 Oct 29 09:32 bin
drwxr-xr-x 5 root root  4096 Oct  9 19:43 cmd
drwxr-xr-x 3 root root  4096 Oct  9 19:43 config
drwxr-xr-x 7 root root  4096 Oct  9 19:43 docker
drwxr-xr-x 6 root root  4096 Oct  9 19:43 docs
-rw-r--r-- 1 root root  1314 Oct  9 19:43 go.mod
-rw-r--r-- 1 root root 21123 Oct  9 19:43 go.sum
-rw-r--r-- 1 root root  1076 Oct  9 19:43 LICENSE
-rw-r--r-- 1 root root  1100 Oct  9 19:43 package.json
drwxr-xr-x 5 root root  4096 Oct  9 19:43 pkg
drwxr-xr-x 2 root root  4096 Oct  9 19:43 public
-rw-r--r-- 1 root root  5570 Oct  9 19:43 README.md
-rwxr-xr-x 1 root root   299 Oct  9 19:43 release.sh
drwxr-xr-x 7 root root  4096 Oct  9 19:43 src
[root@k8s-master-15-81 kt-connect-kt-0.0.6]# go build -o "output/ktctl/ktctl" ./cmd/ktctl
go: finding github.com/deckarep/golang-set v1.7.1
go: finding github.com/jessevdk/go-assets v0.0.0-20160921144138-4f4301a06e15
go: finding github.com/imdario/mergo v0.3.7
go: finding github.com/thinkerou/favicon v0.1.0
go: finding github.com/rs/zerolog v0.0.0-20190704061603-77a169535877
go: finding github.com/gorilla/websocket v1.4.1
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/campoy/embedmd v0.0.0-20171205015432-c59ce00e0296
go: finding github.com/gin-gonic/autotls v0.0.0-20180426091246-be87bd5ef97b
go: finding github.com/urfave/cli v0.0.0-20190203184040-693af58b4d51
go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: finding github.com/zenazn/goji v0.9.0
go: finding github.com/miekg/dns v0.0.0-20190106042521-5beb9624161b
go: k8s.io/apimachinery@v0.0.0-20190717022731-0bb8574e0887: unrecognized import path "k8s.io/apimachinery" (https fetch: Get https://k8s.io/apimachinery?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/utils@v0.0.0-20190712204705-3dccf664f023: unrecognized import path "k8s.io/utils" (https fetch: Get https://k8s.io/utils?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/kubernetes/dashboard v1.10.1
go: golang.org/x/lint@v0.0.0-20181011164241-5906bd5c48cd: unrecognized import path "golang.org/x/lint" (https fetch: Get https://golang.org/x/lint?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/dustin/go-broadcast v0.0.0-20171205050544-f664265f5a66
go: finding github.com/manucorporat/stats v0.0.0-20180402194714-3ba42d56d227
go: golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/rs/xid v1.2.1
go: google.golang.org/grpc@v1.15.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/gin-gonic/gin v1.4.0
go: k8s.io/api@v0.0.0-20190717022910-653c86b0609b: unrecognized import path "k8s.io/api" (https fetch: Get https://k8s.io/api?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: golang.org/x/tools@v0.0.0-20190425163242-31fd60d6bfdc: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: error loading module requirements
[root@k8s-master-15-81 kt-connect-kt-0.0.6]#

可以直接提供一下二进制包吗？
我在这个链接下载的是0.0.4版本的
https://rdc-incubators.oss-cn-beijing.aliyuncs.com/stable/ktctl_linux_amd64.tar.gz
可以提供一下最新二进制包下载路径吗？

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.5]
 - Kubernetes [e.g. 1.15.1]
 - KT Version [e.g. 0.0.6]

**Additional context**

**Comment by yunlzheng** [comment]
@sandshell 在https://github.com/alibaba/kt-connect/releases可以下载最新的构建包，编译报错应该是因为网络问题，没有下载到k8s.io的包
