### ISSUE TITLE
connect时能否包含多个namespace的service?

### ISSUE THREAD

**Issue by ystyle** [alibaba/kt-connect#321]
**Is your feature request related to a problem? Please describe.**
无关 

**Describe the solution you'd like**
如题， connect时现在默认是default， 但指定namespace后又只能访问该命名空间下的服务， 能否做到在connect时同时指定多个命名空间？（我现在用的是--dnsMode hosts模式）

**Describe alternatives you've considered**

**Additional context**

**Comment by linfan** [comment]
hosts DNS模式可以用 `:ns1,ns2` 这种格式指定多个namespace，比如：`--dnsMode hosts:default,dev,test`

在文档的参数说明里有提到 https://alibaba.github.io/kt-connect/#/zh-cn/cli/connect
