### ISSUE TITLE
支持本地访问集群的ingress

### ISSUE THREAD

**Issue by CoderTDK** [alibaba/kt-connect#322]
目前本地打通dev k8s后，能正常访问到pod的IP，但是访问不了集群的ingress地址。目前我们有同一个集群内部服务之间通过ingress访问的场景，希望能支持。

**Comment by linfan** [comment]
已在`v0.3.6`版本支持，需要在运行`ktctl connect`命令时使用`--ingressIp`参数指定Ingress的IP地址。kt-connect会自动读取当前Namespace下的所有Ingress域名，自动解析到这个IP上。

**Comment by wsw** [comment]
配置上--ingressIp后，还是访问不了，其中报这个：the server could not find the requested resource (get ingresses.extensions)
