### ISSUE TITLE
kt启动失败：failed to add ip addr 10.106.202.0 to tun device

### ISSUE THREAD

**Issue by shenzhiqin91** [alibaba/kt-connect#324]
<img width="605" alt="kterror" src="https://user-images.githubusercontent.com/106303788/174218739-54d816ae-3820-49ec-86e3-132544a4b4e1.png">

**Comment by linfan** [comment]
这种情况一般是本地还运行了其他网络管理软件，并且也配置了Kubernetes的Service和Pod所在网段的路由，比如VPN或者其他用于打通集群网络的工具。

可以使用`ipconfig /all`命令查看各网卡的IP地址，然后通过`route print`命令查看路由表信息，路由表的Interface IP就是网卡的IP，查看是哪个网卡已经在使用这些网段了。

**Comment by shenzhiqin91** [comment]
> 这种情况一般是本地还运行了其他网络管理软件，并且也配置了Kubernetes的Service和Pod所在网段的路由，比如VPN或者其他用于打通集群网络的工具。
> 
> 可以使用`ipconfig /all`命令查看各网卡的IP地址，然后通过`route print`命令查看路由表信息，路由表的Interface IP就是网卡的IP，查看是哪个网卡已经在使用这些网段了。

**Comment by shenzhiqin91** [comment]
看了下，不是这个原因，还有其它原因嘛，在两个环境都出现了这种问题。下面是完整日志
![kterror](https://user-images.githubusercontent.com/106303788/174245112-60611c0c-7561-4fb0-a472-63fe0b2d10fe.jpg)

**Comment by shenzhiqin91** [comment]
> 这种情况一般是本地还运行了其他网络管理软件，并且也配置了Kubernetes的Service和Pod所在网段的路由，比如VPN或者其他用于打通集群网络的工具。
> 
> 可以使用`ipconfig /all`命令查看各网卡的IP地址，然后通过`route print`命令查看路由表信息，路由表的Interface IP就是网卡的IP，查看是哪个网卡已经在使用这些网段了。

看了下，不是这个原因，还有其它原因嘛，在两个环境都出现了这种问题。下面是完整日志：
![kterror](https://user-images.githubusercontent.com/106303788/174245457-63b2078a-7ab2-4b40-8650-2fe561382914.jpg)

**Comment by shenzhiqin91** [comment]
> 这种情况一般是本地还运行了其他网络管理软件，并且也配置了Kubernetes的Service和Pod所在网段的路由，比如VPN或者其他用于打通集群网络的工具。
> 
> 可以使用`ipconfig /all`命令查看各网卡的IP地址，然后通过`route print`命令查看路由表信息，路由表的Interface IP就是网卡的IP，查看是哪个网卡已经在使用这些网段了。

@linfan  看了下，不是这个原因，还有其它原因嘛? 在两个环境都出现了这种问题。下面是完整日志：
![kterror](https://user-images.githubusercontent.com/106303788/174249634-91c1b078-475d-4127-a6fc-67287cef23f5.jpg)
![routeprint](https://user-images.githubusercontent.com/106303788/174249932-ae59bf06-4115-47e5-a800-1456718eecc2.jpg)

**Comment by linfan** [comment]
这就确实挺奇怪的了，可以试一下加上`--disableTunRoute`参数启动：

```
ktctl connect --disableTunRoute
```

然后另开一个命令行，手工执行一下在Debug日志上报错的命令，看看有什么错误信息：

```
netsh interface ipv4 set address KtConnectTunnel static 10.106.202.0 225.225.225.0
netsh interface ipv4 set address KtConnectTunnel 10.100.135.110 225.225.225.225
```

或是在Debug日志的第一行，把输出的那个`Background task log to`后面的那个文件打开，看一下里面有没什么报错信息。

**Comment by shenzhiqin91** [comment]
@linfan 现在发现是Tunnel创建后就被电脑删掉或禁用了，有什么原因会导致这个问题出现呢？是银行开发环境，可能是电脑的安全防护软件造成的吗？

**Comment by shenzhiqin91** [comment]
@linfan 现在发现是Tunnel创建后就被电脑删掉或禁用了，有什么原因会导致这个问题出现呢？是银行开发环境，可能是电脑的安全防护软件造成的吗？以下是相关日志：
![Uploading kterror3.png…]()

**Comment by shenzhiqin91** [comment]
现在发现是Tunnel创建后就被电脑删掉或禁用了，有什么原因会导致这个问题出现呢？是银行开发环境，可能是电脑的安全防护软件造成的吗？以下是相关日志：
<img width="597" alt="kterror3" src="https://user-images.githubusercontent.com/106303788/174513844-c815fc93-a98b-4c94-975b-ab738924139f.png">

**Comment by linfan** [comment]
DBG 开头的日志报错可以忽略，这些是在加`--debug`参数才会显示的信息，属于对运行没有影响的错误。

红框里的前两条日志是本地有服务查询"www.microsoft.com"域名的SOA记录，但这是个A记录域名，所以确实查不到SOA记录，所以报了Fail。最后一条是用于探测本地与集群时间时差的临时Pod在执行完任务之后正常关闭打印的日志。

最后这个截屏看起来应该已经正常运行了吧？

**Comment by linfan** [comment]
无法创建虚拟网卡的话，除了`connect`之外的其他功能不受影响。

如果依然要用`connect`的话，只能加`--disableTunDevice`禁用掉本地创建虚拟网卡的操作，这种情况下KT只会建立一个通往集群的socks5代理通道，但不会创建网卡并配置路由来让访问集群的请求自动使用这个通道，需要本地服务自己配置代理才能访问集群的地址（KT在运行后会在屏幕上打印代理的地址）。在Windows下有些浏览器可以添加socks5代理，比如火狐、Chrome、较高版本的Edge等，具体配置方法可用搜索网络，但并非所有软件都内置有使用代理的功能。

**Comment by shenzhiqin91** [comment]
@linfan 加上--disableTunDevice后，启动失败
![image](https://user-images.githubusercontent.com/106303788/174727752-099366a8-dcae-4893-b602-68f527ed624d.png)

**Comment by shenzhiqin91** [comment]
@linfan 
以ktctl connect --disableTunDevice --dnsMode=hosts启动kt-connect后，并在chrome中配置好socks5代理，还是不能ping通pod的ip

<img width="534" alt="01" src="https://user-images.githubusercontent.com/106303788/174748880-e0980824-7952-44ca-9143-30adabcc1abd.png">
<img width="541" alt="02" src="https://user-images.githubusercontent.com/106303788/174749472-fe3e0eba-81bf-42f7-9f64-107491c700ee.png">
<img width="823" alt="03" src="https://user-images.githubusercontent.com/106303788/174749507-dd17bca5-c30a-4659-8014-99da6791e00b.png">
<img width="694" alt="04" src="https://user-images.githubusercontent.com/106303788/174749528-80969a52-4a1c-462f-8323-a9353162da98.png">

**Comment by linfan** [comment]
@shenzhiqin91 在使用`--disableTunDevice`参数的情况下，只有显示设置了代理的软件才能访问集群。比如浏览器在配置sock5代理以后，浏览器自身就可以访问集群的IP和域名了。但其他软件，比如控制台的ping是依然无法访问集群网络的。

**Comment by linfan** [comment]
`Failed to set dns server of tun device` 这个问题我加个检查吧，在禁用本地KT网卡的情况下，Windows环境确实是不支持使用 localDNS 模式的

**Comment by linfan** [comment]
已在`v0.3.6`版本增加禁用tun设备时自动切换为hosts dns模式逻辑

**Comment by shenzhiqin91** [comment]
> 

@linfan 如果加--disableTunDevice禁用掉本地创建虚拟网卡，还有办法ping通pod的ip吗
