### ISSUE TITLE
不支持 {name}.{namespace}.svc

### ISSUE THREAD

**Issue by jiuker** [alibaba/kt-connect#325]
不支持 {name}.{namespace}.svc
在pod里面是支持这种访问的。
打了隧道以后，这种service不支持
但是 {name}.{namespace}.svc.cluster.local 是支持的

**Comment by linfan** [comment]
这种域名我们在 v0.3.6 增加支持吧

**Comment by linfan** [comment]
fixed in `v0.3.6`
