### ISSUE TITLE
本地无法使用namespace访问service

### ISSUE THREAD

**Issue by duanmengkk** [alibaba/kt-connect#326]
**Describe the bug**

按照文档创建了tomcat，可以直接通过svc访问，但是无法通过svc.namespace 访问
![image](https://user-images.githubusercontent.com/17697155/174756956-342e7d66-17ea-43db-bfdf-c6920967e4da.png)

**Log**
please add -d to debug log

**Environment (please complete the following information):**
 - Kubernetes [1.18.5]
 - KT Version [0.3.5]

**Additional context**

**Comment by duanmengkk** [comment]
@linfan

**Comment by linfan** [comment]
加 --debug 参数启动，然后在访问 tomcat.default 域名的时候，看一下 ktctl 的窗口是否有什么错误输出？

**Comment by linfan** [comment]
暂无更多信息输入，先关闭，如果有其他新增信息，请Reopen
