### ISSUE TITLE
执行ktctl connect时ERR Failed to setup port forward local:

### ISSUE THREAD

**Issue by liujiyuan** [alibaba/kt-connect#327]
ERR Failed to setup port forward local:16562 -> pod kt-connect-shadow-juxkw:53 error="error upgrading connection: error sending request: Post \"https://192.168.11.50/k8s/clusters/c-xv2pt/api/v1/namespaces/default/pods/kt-connect-shadow-juxkw/portforward\": dial tcp 192.168.11.50:443: connectex: A socket operation was attempted to an unreachable host."
这是哪里没配对吗？

**Comment by linfan** [comment]
麻烦提供一下带 --debug 参数运行的完整日志

**Comment by liujiyuan** [comment]
Forwarding from 127.0.0.1:36763 -> 22
Forwarding from [::1]:36763 -> 22
time="2022-06-23T22:03:10+08:00" level=info msg="[STACK] tun://KtConnectTunnel <-> socks5://127.0.0.1:2223"
time="2022-06-23T22:03:10+08:00" level=warning msg="[STACK] udp forwarder request fe80::c7d:6030:7be:3e0c:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:10+08:00" level=warning msg="[STACK] udp forwarder request fe80::c7d:6030:7be:3e0c:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:10+08:00" level=warning msg="[STACK] udp forwarder request fe80::c7d:6030:7be:3e0c:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:10+08:00" level=warning msg="[STACK] udp forwarder request fe80::c7d:6030:7be:3e0c:5353->ff02::fb:5353: network is unreachable"
>> Get interfaces: 
Idx     Met         MTU          ״̬                    
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 12           5       65535  connected     KtConnectTunnel
 11          15        1500  connected       ̫  
  9          25        1500  disconnected          


>> Get route: 
                 Ծ     ǰ׺                              / ӿ     
------- -------- ---    ------------------------ --- ------------------------
                      Ĭ     10.43.0.0/16               12  10.43.0.0
                      Ĭ     10.42.0.0/16               12  10.42.0.0
                      Ĭ     192.168.11.0/24            12  192.168.11.0


time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::25e0:de1f:2488:b421:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::4df2:bbae:f1eb:571c:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::4df2:bbae:f1eb:571c:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:11+08:00" level=warning msg="[STACK] udp forwarder request fe80::4df2:bbae:f1eb:571c:55300->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:12+08:00" level=warning msg="[STACK] udp forwarder request fe80::4df2:bbae:f1eb:571c:55300->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:12+08:00" level=warning msg="[STACK] udp forwarder request fe80::dd6e:d1fe:6cdc:400b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:12+08:00" level=warning msg="[STACK] udp forwarder request fe80::dd6e:d1fe:6cdc:400b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:12+08:00" level=warning msg="[STACK] udp forwarder request fe80::dd6e:d1fe:6cdc:400b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:12+08:00" level=warning msg="[STACK] udp forwarder request fe80::dd6e:d1fe:6cdc:400b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:58941->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::d536:59e0:bdca:eff7:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request 10.43.0.0:5353->224.0.0.251:5353: no route"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::ac83:955a:fe42:1760:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request 10.43.0.0:5353->224.0.0.251:5353: no route"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::ac83:955a:fe42:1760:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request 10.43.0.0:5353->224.0.0.251:5353: no route"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::ac83:955a:fe42:1760:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request fe80::ac83:955a:fe42:1760:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:13+08:00" level=warning msg="[STACK] udp forwarder request 10.43.0.0:5353->224.0.0.251:5353: no route"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:64193->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:14+08:00" level=warning msg="[STACK] udp forwarder request fe80::c38:5854:4196:afa:56051->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:17+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:17+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:17+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:17+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:17+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:61415->ff02::1:3:5355: network is unreachable"
time="2022-06-23T22:03:18+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:18+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:21+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:21+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:22+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
time="2022-06-23T22:03:22+08:00" level=warning msg="[STACK] udp forwarder request fe80::4402:51bd:dedb:b16b:5353->ff02::fb:5353: network is unreachable"
Handling connection for 36763
>> Get interfaces: 
Idx     Met         MTU          ״̬                    
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 12           5       65535  connected     KtConnectTunnel
 11          15        1500  connected       ̫  
  9          25        1500  disconnected          


>> Get route: 
                 Ծ     ǰ׺                              / ӿ     
------- -------- ---    ------------------------ --- ------------------------
                      Ĭ     10.43.0.0/16               12  10.43.0.0
                      Ĭ     10.42.0.0/16               12  10.42.0.0
                      Ĭ     192.168.11.0/24            12  192.168.11.0


time="2022-06-23T22:03:23+08:00" level=info msg="[TCP] 192.168.11.0:59998 <-> 192.168.11.50:443"
Forwarding from 127.0.0.1:7432 -> 53
Forwarding from [::1]:7432 -> 53
time="2022-06-23T22:03:23+08:00" level=info msg="[TCP] 192.168.11.0:60001 <-> 192.168.11.50:443"

**Comment by liujiyuan** [comment]
上面有乱码，再贴一下附件

**Comment by liujiyuan** [comment]
可能是k8s集群网络和我本地网络问题，换了一个网的k8s集群就可以了。

**Comment by liujiyuan** [comment]
可能是k8s集群网络和我本地网络问题。
解决方案：换了一个网的k8s集群就可以了。或者换一台本机电脑也可以了。
请问下面这个请求（也就是报错的请求），是从k8s的node电脑发出的，还是从我的本机电脑发出的？
Post "[https://192.168.11.50/k8s/clusters/c-xv2pt/api/v1/namespaces/default/pods/kt-connect-shadow-juxkw/portforward\](https://192.168.11.50/k8s/clusters/c-xv2pt/api/v1/namespaces/default/pods/kt-connect-shadow-juxkw/portforward%5C)": 
如果是从k8s的node发出的，那么换一台本地电脑不应该好；如果是从我本机电脑发出的，可是我本地电脑是能访问192.168.11.50。真是很矛盾，很奇怪。

**Comment by linfan** [comment]
这个POST请求是从本地电脑发出的。
需要一个加`--debug`之后屏幕打印的日志哈，不是那个日志文件里的（日志文件是后台任务输出），初步判断可能和本地KT网卡的路由范围合并算法有关系，可能是误将k8s server的IP所在网段也配置到了KT网卡，但需要通过日志进一步判断
