### ISSUE TITLE
各版本的shadow能否调整一下shadow的deployment的ImagePullPolicy策略，目前新版的也还是Always

### ISSUE THREAD

**Issue by little-hang** [alibaba/kt-connect#337]
能否调整一下shadow的deployment的ImagePullPolicy策略，目前为Always，这在内网环境上影响很大，即使本地已经有相应的镜像，也需要联网下载，导致pod一直在pending状态 。
---看历史的issue里也提到了这个建议，不过从官网下载的最新ktctl版本ktctl_0.3.6，ImagePullPolicy策略还是Always，这个策略的修改没有merge到后续新版本中么

**Comment by linfan** [comment]
刚刚实测了 0.3.6 版本默认的 imagePullPolicy 是 IfNotPresent，只有加上 `--forceUpdate` 参数的时候才会变成 Always

**Comment by linfan** [comment]
确认一下是否通过 ktctl config 设置了默认参数或者集群里有 WebHook 修改了创建Pod的属性。我这边实测不论是使用 Shadow Pod 或者 Shadow Deployment （使用 `--useShadowDeployment` 参数），创建出的 imagePullPolicy 都应该是 IfNotPresent

**Comment by little-hang** [comment]
感谢如此及时的回复。的确如你所说，新版已经是 IfNotPresent。我刚才的原因是：之前设置了KUBERNETES_MASTER的环境变量指定了 ktctl config（被其他人冲掉了），显示带上--kubeconfig=***，看上去镜像拉取OK了
