### ISSUE TITLE
有没有最小权限模板？

### ISSUE THREAD

**Issue by ystyle** [alibaba/kt-connect#340]
如题， 需要给外部人开放kt connect权限， 但不希望他们有太多的权限，能正常使用ktctl connect 就行了。 
最好能指定能连接的services这部分权限我知道怎么选择，但ktctl本身需要哪些权限？

**Comment by linfan** [comment]
见文档 https://alibaba.github.io/kt-connect/#/zh-cn/reference/authorization

**Comment by ystyle** [comment]
好的，谢谢

**Comment by ystyle** [comment]
好的，谢谢
