### ISSUE TITLE
Can't Access Server via internal DNS address

### ISSUE THREAD

**Issue by Cloud0ps** [alibaba/kt-connect#36]
**Describe the bug**
Access via IP ok
Can't Access Server via internal DNS address

Error:
vm:~$ curl http://tomcat.default.svc.cluster.local:8080
curl: (6) Could not resolve host: tomcat.default.svc.cluster.local

DNS request from ('192.168.160.128', 55699) to None: 43 bytes

**Log**
vm:~/.kube$ ktctl connect namespace test
3:50PM INF Daemon Start At 14194
3:50PM INF Client address 192.168.160.128
3:50PM INF Shadow is ready.
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 2.7.12
c : connecting to server...
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
c : Connected.
Starting server with Python version 3.5.2
 s: latency control setting = True
 s: auto-nets:False
firewall manager: setting up.
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.244.0.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.100.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.96.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.108.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.102.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.99.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.104.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.98.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.97.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.103.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.105.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.101.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.107.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.111.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.109.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.106.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 10.110.0.0/16 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 114.114.114.114/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.0.2/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
c : DNS request from ('192.168.160.128', 41908) to None: 41 bytes
c : DNS request from ('192.168.160.128', 41908) to None: 41 bytes
c : DNS request from ('192.168.160.128', 51766) to None: 53 bytes
c : DNS request from ('192.168.160.128', 51766) to None: 53 bytes
c : DNS request from ('192.168.160.128', 47463) to None: 37 bytes
c : DNS request from ('192.168.160.128', 47463) to None: 37 bytes
c : DNS request from ('192.168.160.128', 41140) to None: 49 bytes
c : DNS request from ('192.168.160.128', 41140) to None: 49 bytes
c : DNS request from ('192.168.160.128', 35257) to None: 50 bytes
c : DNS request from ('192.168.160.128', 35257) to None: 50 bytes
c : DNS request from ('192.168.160.128', 37780) to None: 62 bytes
c : DNS request from ('192.168.160.128', 37780) to None: 62 bytes
c : Accept TCP: 192.168.160.128:42278 -> 10.111.211.232:80.
 s: SW#6:10.111.211.232:80: uwrite: got EPIPE
c : Accept TCP: 192.168.160.128:41788 -> 10.102.89.241:80.
c : SW#8:192.168.160.128:42278: deleting (3 remain)
c : SW'unknown':Mux#13: deleting (2 remain)
c : Accept TCP: 192.168.160.128:41844 -> 10.102.89.241:80.
c : SW#11:192.168.160.128:41788: deleting (3 remain)
c : SW'unknown':Mux#14: deleting (2 remain)
c : DNS request from ('192.168.160.128', 50877) to None: 29 bytes
c : SW#8:192.168.160.128:41844: deleting (1 remain)
c : SW'unknown':Mux#15: deleting (0 remain)
c : DNS request from ('192.168.160.128', 39003) to None: 29 bytes
c : DNS request from ('192.168.160.128', 51747) to None: 43 bytes
c : DNS request from ('192.168.160.128', 35325) to None: 43 bytes

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04] Ubuntu 18.04.3 LTS
 - Kubernetes [e.g. 1.10.1] 1.12.5
 - KT Version [e.g. 0.0.4] KT Connect version 0.0.6

**Additional context**

**Comment by yunlzheng** [comment]
Could you please provide the shadow container log.

**Comment by Cloud0ps** [comment]
root@vm:~# cat /data/docker/containers/409e879ebe21081b82a89812b4b04bcccd79656ec4e4911e3de7267ad222c14a/409e879ebe21081b82a89812b4b04bcccd79656ec4e4911e3de7267ad222c14a-json.log
{"log":"\u001b[90m1:54AM\u001b[0m \u001b[32mINF\u001b[0m Start kt connect proxy\n","stream":"stderr","time":"2019-11-05T01:54:27.233022665Z"}
{"log":"\u001b[90m1:54AM\u001b[0m \u001b[32mINF\u001b[0m SSHD start at pid: 10\n","stream":"stderr","time":"2019-11-05T01:54:27.237470538Z"}
{"log":"\n","stream":"stderr","time":"2019-11-05T01:54:27.237509957Z"}
{"log":"\u001b[90m1:54AM\u001b[0m \u001b[32mINF\u001b[0m Successful load local /etc/resolv.conf\n","stream":"stderr","time":"2019-11-05T01:54:27.237938346Z"}
{"log":"\u001b[90m1:54AM\u001b[0m \u001b[32mINF\u001b[0m Success load nameserver 10.96.0.10\n","stream":"stderr","time":"2019-11-05T01:54:27.238306942Z"}
{"log":"\n","stream":"stderr","time":"2019-11-05T01:54:27.23832218Z"}
{"log":"DNS Server Start At 53...\n","stream":"stdout","time":"2019-11-05T01:54:27.238375249Z"}
root@vm:~# kubectl logs kt-connect-daemon-kcwcu-648878b778-tdfbg -f                                                                                                                       
1:54AM INF Start kt connect proxy
1:54AM INF SSHD start at pid: 10

1:54AM INF Successful load local /etc/resolv.conf
1:54AM INF Success load nameserver 10.96.0.10

DNS Server Start At 53...

**Comment by zhangxpp** [comment]
same issue, on CentOS Linux release 7.5.1804, with kernel 3.10.0-862.el7.x86_64

**Comment by npchp110** [comment]
same issue, on macOS 10.13.6
couldnot access server via service name when using kt-connect, 
```
➜  ~ telnet nlu-es-slb 9209
nlu-es-slb: nodename nor servname provided, or not known
```
but it worked when using telepresence.
```
➜  ~ telnet nlu-es-slb 9209
Trying 10.105.192.195...
Connected to nlu-es-slb.lan.
Escape character is '^]'.
```

**Comment by linfan** [comment]
老的ktctl dns服务实现问题，新版本已修复
