### ISSUE TITLE
curl 服务名+端口 超时

### ISSUE THREAD

**Issue by xjh1994** [alibaba/kt-connect#362]
**Describe the bug**
telnet 服务名+端口都通，ping pod ip也通，但是通过curl 或者浏览器访问 服务名+端口，一直超时，pod ip+端口也一样。日志能看到的报错只有这行，看起来是连kt的pod失败了，但是ping kt pod 10.233.70.24这个ip和telnet都是通的

**Log**
`Socks proxy heartbeat interrupted error="socks connect tcp 127.0.0.1:2223->10.233.70.24:22: unknown error host unreachable"`

**Environment (please complete the following information):**
 - OS: Windows10
 - Kubernetes 1.20.4
 - KT Version 0.3.6

**Additional context**

**Comment by jia2118290** [comment]
这个问题解决了吗？遇到相同的问题

**Comment by xjh1994** [comment]
> 这个问题解决了吗？遇到相同的问题

解决了，是集群节点没有装socat @jia2118290

**Comment by OAMchronicle** [comment]
> > 这个问题解决了吗？遇到相同的问题
> 
> 解决了，是集群节点没有安装socat@jia2118290

我并没有在文档中找到安装`socat`  ，请问这个如何安装使用

**Comment by xjh1994** [comment]
ubuntu上是执行命令 apt install socat，其他系统可以搜一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月5日(周一) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [alibaba/kt-connect] curl 服务名+端口 超时 (Issue #362)




   
这个问题解决了吗？遇到相同的问题
  
***@***.***
  
我并没有在文档中找到安装socat  ，请问这个如何安装使用

**Comment by OAMchronicle** [comment]
> ubuntu上是执行命令apt install socat，其他系统可以搜索一下
> [……](#)
> ---原始邮件--- 发件人: ***@***.***> 发送时间: 2022年12月5日(周一)下午2:26 收件人: ***@***.***>; 抄送: ***@***.***>;"状态 ***@***.***>; 主题: Re: [alibaba/kt-connect] curl 服务名+端口 超时(Issue #362 ) 这个问题解决了吗？遇到相同的问题 ***@***.*** 我并没有在文档中找到安装socat ，请问这个如何安装使用 — 直接回复此邮件，查看它在 GitHub 上，或取消订阅。您收到此消息是因为您修改了打开/关闭状态。消息 ID：***@***.***>

我找到了，这个是一个单独的组件而非是ktctl

**Comment by OAMchronicle** [comment]
非常感谢

**Comment by OAMchronicle** [comment]
我在欧拉的机器上没有这个服务，我自己编译完成之后还是报这个错误

**Comment by liqiao7** [comment]
同样的问题，在节点安装socat后有效。

**Comment by OAMchronicle** [comment]
> 同样的问题，在节点安装socat后有效。

你是不是编译安装的

默认编译安装socat在 /usr/local/bin ，rpm安装的在/usr/bin/下
你做个软连接过去试试。默认安装的应该是三个软件 全部做软链再试一下

**Comment by maxid** [comment]
> > 这个问题解决了吗？遇到相同的问题
> 
> 解决了，是集群节点没有装socat @jia2118290

有用，感谢

**Comment by akii90** [comment]
> > 解决了，是集群节点没有装socat @jia2118290
> 
> 有用，感谢

我的集群节点上都有socat，还是无法连接端口，windows的机器上也需要安装吗

**Comment by tianyunfari** [comment]
> > > 解决了，是集群节点没有装socat @jia2118290
> > 
> > 
> > 有用，感谢
> 
> 我的集群节点上都有socat，还是无法连接端口，windows的机器上也需要安装吗

你好，请问解决了吗？我的k8s版本是1.30，master节点已经装了socat还是不行
