### ISSUE TITLE
不知道这个与 Telepresence 的区别？

### ISSUE THREAD

**Issue by polyrabbit** [alibaba/kt-connect#38]
[Telepresence](https://www.telepresence.io/) 看起来也是解决本地与集群环境中调试的问题，不知道 kt-connect 与 Telepresence 的区别及联系是什么？

附一篇 telepresence 的中文简介：
https://blog.betacat.io/post/develop-and-debug-k8s-microservices-locally-using-telepresence/

**Comment by yunlzheng** [comment]
解决的基本问题是一致的，不过场景上kt connect考虑的更多是协作开发。Telepresence适用于单人独占环境，kt connect支持多人共享环境，方式上是基于service mesh。 对标的话是azure的dev-spaces https://docs.microsoft.com/en-us/azure/dev-spaces/

**Comment by polyrabbit** [comment]
OK，明白了，感谢解答。
