### ISSUE TITLE
release应该持续包含 windows 版本，

### ISSUE THREAD

**Issue by hala21** [alibaba/kt-connect#49]
绝大多数的开发环境是windows，假如能持续发布windows版本，用户量应该会大增。

**Comment by yunlzheng** [comment]
在老版本中因为依赖了sshuttle导致在windows下使用会有问题。 0.0.7中新增了socks5代理模式，在windows下测试完成后后续release会新增windows的exe，感谢反馈

**Comment by yunlzheng** [comment]
https://github.com/alibaba/kt-connect/issues/53

**Comment by yunlzheng** [comment]
@hala21   windows exe版本的可执行包在这里可以下载。 https://alibaba.github.io/kt-connect/#/zh-cn/nightly 

目前windows下只支持socks5代理模式。

```
ktctl connect --method socks5
```

**Comment by yunlzheng** [comment]
0.0.8版本以包含windows的release
