### ISSUE TITLE
panic: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by vinci7** [alibaba/kt-connect#5]
go version
`go version go1.12.6 darwin/amd64`
ktctl version
`Kubernetes Develope Tools version 0.0.4`

kubectx 指向GCP的cluster
![image](https://user-images.githubusercontent.com/3354532/61601400-1c24d000-ac70-11e9-98cb-0d899b4c89bb.png)
已通过gcloud账户授权

![image](https://user-images.githubusercontent.com/3354532/61601267-ab7db380-ac6f-11e9-881f-637d2dbb8ff9.png)
使用kt时出现以上报错

**Comment by yunlzheng** [comment]
本地直接使用kubectl能正常使用吗？

**Comment by vinci7** [comment]
@yunlzheng 谢谢回复，kubectl可以正常使用

![image](https://user-images.githubusercontent.com/3354532/61683978-ad6c7300-ad52-11e9-9bfa-ed37db9e690a.png)

**Comment by fudali113** [comment]
> @yunlzheng 谢谢回复，kubectl可以正常使用
> 
> ![image](https://user-images.githubusercontent.com/3354532/61683978-ad6c7300-ad52-11e9-9bfa-ed37db9e690a.png)

你可以试着运行 kubectl 获取 `node`, `service` 资源和创建 `deployment，pod` 看看是否会报错呢？

**Comment by vinci7** [comment]
@fudali113 谢谢回复，你提到的操作均未遇到报错，比如

![image](https://user-images.githubusercontent.com/3354532/61736875-03c4ca80-adc2-11e9-9ab0-f39db33b5044.png)

**Comment by yunlzheng** [comment]
see https://github.com/kubernetes/client-go/issues/242
@vinci7 @fudali113  需要client_go需要引入gcp的auth插件，会尽快修复，谢谢！

**Comment by yunlzheng** [comment]
@see https://github.com/alibaba/kt-connect/releases/tag/v0.0.5
