### ISSUE TITLE
[Doc] How to create custom kubeConfig for ktctl

### ISSUE THREAD

**Issue by yunlzheng** [alibaba/kt-connect#62]

**Comment by zeusro** [comment]
You means kubeConfig for our serviceaccount ?

**Comment by yunlzheng** [comment]
Yes
> You means kubeConfig for our serviceaccount ?

**Comment by zeusro** [comment]
可以参考

http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/

https://kubernetes.io/zh/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

有点麻烦。

**Comment by eliu** [comment]
我之前写了一个脚本，不过不是针对serviceaccount的，是针对某个用户的：
https://github.com/eliu/kt-connect-rbac

**Comment by linfan** [comment]
Doc added:
- 集群权限：https://alibaba.github.io/kt-connect/#/zh-cn/reference/authorization
- 企业定制：https://alibaba.github.io/kt-connect/#/zh-cn/reference/customize
