### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by dchack** [alibaba/kt-connect#66]
**Describe the bug**
sudo ktctl connect 命令的日志和文档描述不一致，尝试使用crul请求远程集群的pod也请求不通（mac系统按照文档安装）

**Log**
1:40PM INF Daemon Start At 72299
1:40PM INF Client address 192.168.4.19
1:40PM INF Deploying shadow deployment kt-connect-daemon-agfnp in namespace default

1:41PM INF Shadow is ready.
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.1
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('::1', 12299, 0, 0).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.1
c : connecting to server...
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
Starting server with Python version 3.5.2
 s: latency control setting = True
 s: auto-nets:False
c : Connected.
firewall manager: setting up.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : DNS request from ('192.168.4.19', 64619) to None: 40 bytes
c : DNS request from ('192.168.4.19', 54159) to None: 60 bytes
c : DNS request from ('192.168.4.19', 63031) to None: 36 bytes

**Comment by yunlzheng** [comment]
@dchack 麻烦使用 sudo ktctl -d connect  提供一下包含debug信息的日志

**Comment by dchack** [comment]
> sudo ktctl -d connect

1:59PM INF Daemon Start At 74865
1:59PM INF Client address 192.168.4.19
1:59PM INF Deploying shadow deployment kt-connect-daemon-oslta in namespace default

1:59PM DBG Shadow Pods not ready......
1:59PM DBG Shadow Pod status is Pending
1:59PM DBG Shadow Pod status is Running
1:59PM INF Shadow is ready.
1:59PM DBG Success deploy proxy deployment kt-connect-daemon-oslta in namespace default

1:59PM DBG Child, os.Args = [ktctl -d connect]
1:59PM DBG Child, cmd.Args = [kubectl --kubeconfig=/Users/dongchao/.kube/config -n default port-forward kt-connect-daemon-oslta-797f8449b8-gj78c 2222:22]
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
1:59PM DBG port-forward start at pid: 74870
2:00PM DBG Child, os.Args = [ktctl -d connect]
2:00PM DBG Child, cmd.Args = [sshuttle --dns --to-ns 172.22.20.62 -v -v -e ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /Users/dongchao/.kt_id_rsa -r root@127.0.0.1:2222 -x 127.0.0.1 172.22.0.0/24 10.1.0.0/16]
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.1
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300 12299
DNS listening on ('::1', 12299, 0, 0).
DNS listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 12299, 0, 0)>.
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12299)>.
Starting client with Python version 3.8.1
c : connecting to server...
c : executing: ['ssh', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-i', '/Users/dongchao/.kt_id_rsa', '-p', '2222', 'root@127.0.0.1', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1106), "assembler.py", "exec"))\'"\'"\'\'']
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (77 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5655 bytes)
server: assembling 'sshuttle.hostwatch' (2385 bytes)
server: assembling 'sshuttle.server' (3830 bytes)
Starting server with Python version 3.5.2
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 3 r=[11] w=[11] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 24, False, '172.22.0.0', 0, 0), (2, 16, False, '10.1.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0), (30, 128, True, '::1', 0, 0)]
firewall manager: Got partial nslist: [(2, '192.168.4.1')]
firewall manager: Got nslist: [(2, '192.168.4.1')]
firewall manager: Got ports: 12300,12300,12299,12299
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
firewall manager: setting up IPv4.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=0/0)
2:00PM DBG vpn(sshuttle) start at pid: 74876
2:00PM DBG KT proxy start successful

**Comment by dchack** [comment]
> @dchack 麻烦使用 sudo ktctl -d connect 提供一下包含debug信息的日志

1:59PM INF Daemon Start At 74865
1:59PM INF Client address 192.168.4.19
1:59PM INF Deploying shadow deployment kt-connect-daemon-oslta in namespace default

1:59PM DBG Shadow Pods not ready......
1:59PM DBG Shadow Pod status is Pending
1:59PM DBG Shadow Pod status is Running
1:59PM INF Shadow is ready.
1:59PM DBG Success deploy proxy deployment kt-connect-daemon-oslta in namespace default

1:59PM DBG Child, os.Args = [ktctl -d connect]
1:59PM DBG Child, cmd.Args = [kubectl --kubeconfig=/Users/dongchao/.kube/config -n default port-forward kt-connect-daemon-oslta-797f8449b8-gj78c 2222:22]
Forwarding from 127.0.0.1:2222 -> 22
Forwarding from [::1]:2222 -> 22
1:59PM DBG port-forward start at pid: 74870
2:00PM DBG Child, os.Args = [ktctl -d connect]
2:00PM DBG Child, cmd.Args = [sshuttle --dns --to-ns 172.22.20.62 -v -v -e ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /Users/dongchao/.kt_id_rsa -r root@127.0.0.1:2222 -x 127.0.0.1 172.22.0.0/24 10.1.0.0/16]
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.1
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
Binding DNS: 12300 12299
DNS listening on ('::1', 12299, 0, 0).
DNS listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 12299, 0, 0)>.
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12299)>.
Starting client with Python version 3.8.1
c : connecting to server...
c : executing: ['ssh', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-i', '/Users/dongchao/.kt_id_rsa', '-p', '2222', 'root@127.0.0.1', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1106), "assembler.py", "exec"))\'"\'"\'\'']
Handling connection for 2222
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (77 bytes)
server: assembling 'sshuttle.helpers' (944 bytes)
server: assembling 'sshuttle.ssnet' (5655 bytes)
server: assembling 'sshuttle.hostwatch' (2385 bytes)
server: assembling 'sshuttle.server' (3830 bytes)
Starting server with Python version 3.5.2
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=7/0)
c : Connected.
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 3 r=[11] w=[11] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
firewall manager: Got subnets: [(2, 24, False, '172.22.0.0', 0, 0), (2, 16, False, '10.1.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0), (30, 128, True, '::1', 0, 0)]
firewall manager: Got partial nslist: [(2, '192.168.4.1')]
firewall manager: Got nslist: [(2, '192.168.4.1')]
firewall manager: Got ports: 12300,12300,12299,12299
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv6.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle6-12300 -f /dev/stdin
>> pfctl -E
firewall manager: setting up IPv4.
>> pfctl -s Interfaces -i lo -v
>> pfctl -s all
>> pfctl -a sshuttle-12300 -f /dev/stdin
>> pfctl -E
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=0/0)
2:00PM DBG vpn(sshuttle) start at pid: 74876
2:00PM DBG KT proxy start successful
c :   Ready: 3 r=[9] w=[] x=[]
c : DNS request from ('192.168.4.19', 53169) to None: 35 bytes
c :  > channel=1 cmd=DNS_REQ len=35 (fullness=0)
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=35/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 43/43
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=35/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=1 cmd=DNS_REQ len=35
 s: Incoming DNS request channel=1.
 s: DNS: sending to '172.22.20.62':0 (try 1)
 s: Waiting: 2 r=[4, 6] w=[] x=[] (fullness=0/0)
 s:   Ready: 2 r=[6] w=[] x=[]
 s: DNS response: 68 bytes
 s:  > channel=1 cmd=DNS_RESPONSE len=68 (fullness=0)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=68/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 76/76
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=68/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=1 cmd=DNS_RESPONSE len=68
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=35/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : DNS request from ('192.168.4.19', 53319) to None: 48 bytes
c :  > channel=2 cmd=DNS_REQ len=48 (fullness=35)
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=83/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 56/56
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=83/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=2 cmd=DNS_REQ len=48
 s: Incoming DNS request channel=2.
 s: DNS: sending to '172.22.20.62':0 (try 1)
 s: Waiting: 2 r=[4, 7] w=[] x=[] (fullness=68/0)
 s:   Ready: 2 r=[7] w=[] x=[]
 s: DNS response: 150 bytes
 s:  > channel=2 cmd=DNS_RESPONSE len=150 (fullness=68)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=218/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 158/158
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=218/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=2 cmd=DNS_RESPONSE len=150
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=83/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : DNS request from ('192.168.4.19', 58715) to None: 48 bytes
c :  > channel=3 cmd=DNS_REQ len=48 (fullness=83)
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=131/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 56/56
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=131/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : DNS request from ('192.168.4.19', 59221) to None: 48 bytes
c :  > channel=4 cmd=DNS_REQ len=48 (fullness=131)
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=179/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 56/56
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=179/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=3 cmd=DNS_REQ len=48
 s: Incoming DNS request channel=3.
 s: DNS: sending to '172.22.20.62':0 (try 1)
 s: Waiting: 2 r=[4, 6] w=[] x=[] (fullness=218/0)
 s:   Ready: 2 r=[4] w=[] x=[]
 s: <  channel=4 cmd=DNS_REQ len=48
 s: Incoming DNS request channel=4.
 s: DNS: sending to '172.22.20.62':0 (try 1)
 s: Waiting: 3 r=[4, 6, 7] w=[] x=[] (fullness=218/0)
 s:   Ready: 3 r=[6] w=[] x=[]
 s: DNS response: 150 bytes
 s:  > channel=3 cmd=DNS_RESPONSE len=150 (fullness=218)
 s: Waiting: 2 r=[4, 7] w=[5] x=[] (fullness=368/0)
 s:   Ready: 2 r=[] w=[5] x=[]
 s: mux wrote: 158/158
 s: Waiting: 2 r=[4, 7] w=[] x=[] (fullness=368/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=3 cmd=DNS_RESPONSE len=150
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=179/0)
 s:   Ready: 2 r=[7] w=[] x=[]
 s: DNS response: 150 bytes
 s:  > channel=4 cmd=DNS_RESPONSE len=150 (fullness=368)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=518/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 158/158
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=518/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=4 cmd=DNS_RESPONSE len=150
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=179/0)

**Comment by yunlzheng** [comment]
@dchack  看日志VPN应该只代理了[172.22.0.0/24 10.1.0.0/16]这两个网段的请求。 看一下访问的PodIP或者ClusterIP是否在这两个网段内。也可以尝试下载最新的ktctl版本，使用socks5代理模式

```
ktctl connect --method=socks5
```

**Comment by yunlzheng** [comment]
先关掉，如果有问题再开
