### ISSUE TITLE
error: invalid resource name "deployments/kt-connect-daemon-gbqts": [may not contain '/']

### ISSUE THREAD

**Issue by DavenAaron** [alibaba/kt-connect#8]
软件版本： 当前最新版 linux客户端

报错信息如下：(kuberntes内 kt-connect-daemon-gbqts 创建正常)
[root@localhost .kube]# ktctl connect
2019/07/23 11:16:04 Client address 192.168.2.40
2019/07/23 11:16:04 Deploying proxy deployment kt-connect-daemon-gbqts in namespace default
2019/07/23 11:16:04 Pod status is Pending
2019/07/23 11:16:06 Pod status is Pending
2019/07/23 11:16:08 Pod status is Running
2019/07/23 11:16:08 Success deploy proxy deployment kt-connect-daemon-gbqts in namespace default
error: invalid resource name "deployments/kt-connect-daemon-gbqts": [may not contain '/']
2019/07/23 11:16:08 port-forward exited
2019/07/23 11:16:10 port-forward start at pid: 16136
Daemon Start At 16127

测试macos 64客户端正常， linux64 报错信息如上

**Comment by yunlzheng** [comment]
谢谢反馈，会尽快修复

**Comment by mojo-zd** [comment]
@DavenAaron 能具体描述一下你的环境吗 
比如linux、docker、kubernetes那个版本

**Comment by yunlzheng** [comment]
@DavenAaron 应该是因为本地的kubectl版本过低，麻烦提供一下kubectl的版本

**Comment by yunlzheng** [comment]
@see https://github.com/alibaba/kt-connect/releases/tag/v0.0.5
