### ISSUE TITLE
Need a warrior to test my code

### ISSUE THREAD

**Issue by zeusro** [alibaba/kt-connect#87]
## old code

```

// remotePortForward mapping local port from cluster
func remotePortForward(expose, kubeconfig, namespace, target, remoteIP string, debug bool) (err error) {
	log.Info().Msgf("remote %s forward to local %s", remoteIP, expose)
	localSSHPort, err := strconv.Atoi(util.GetRandomSSHPort(remoteIP))
	if err != nil {
		return
	}
	portforward := kubectl.PortForward(kubeconfig, namespace, target, localSSHPort)
	err = exec.BackgroundRun(portforward, "exchange port forward to local", debug)
	if err != nil {
		return
	}

	time.Sleep(time.Duration(2) * time.Second)
	log.Printf("SSH Remote port-forward POD %s 22 to 127.0.0.1:%d starting\n", remoteIP, localSSHPort)
	localPort := expose
	remotePort := expose
	ports := strings.SplitN(expose, ":", 2)
	if len(ports) > 1 {
		localPort = ports[1]
		remotePort = ports[0]
	}
	cmd := ssh.ForwardRemoteRequestToLocal(localPort, "127.0.0.1", remotePort, localSSHPort)
	return exec.BackgroundRun(cmd, "ssh remote port-forward", debug)
}
```

## my improvement

```go

// remotePortForward mapping local port from cluster
func remotePortForward(expose, kubeconfig, namespace, target, remoteIP string, debug bool) (err error) {
	log.Info().Msgf("remote %s forward to local %s", remoteIP, expose)
	localSSHPort, err := strconv.Atoi(util.GetRandomSSHPort(remoteIP))
	if err != nil {
		return
	}
	var wg sync.WaitGroup
       wg.Add(1)
	go func(wg *sync.WaitGroup) {
		portforward := kubectl.PortForward(kubeconfig, namespace, target, localSSHPort)
		err = exec.BackgroundRun(portforward, "exchange port forward to local", debug)
		wg.Done()
	}(&wg)
	wg.Wait()
	if err != nil {
		return
	}
	log.Printf("SSH Remote port-forward POD %s 22 to 127.0.0.1:%d starting\n", remoteIP, localSSHPort)
	localPort := expose
	remotePort := expose
	ports := strings.SplitN(expose, ":", 2)
	if len(ports) > 1 {
		localPort = ports[1]
		remotePort = ports[0]
	}
	cmd := ssh.ForwardRemoteRequestToLocal(localPort, "127.0.0.1", remotePort, localSSHPort)
	return exec.BackgroundRun(cmd, "ssh remote port-forward", debug)
}
```

My improvement has no `time.Sleep(time.Duration(2) * time.Second)`,it may be better.

**Comment by yunlzheng** [comment]
ssh.ForwardRemoteRequestToLocal should run after kubectl.PortForward is ready. Otherwise the ssh connection with failed. 

```
5:45PM INF 'KT Connect' not runing, you can only access local app from cluster
5:45PM INF Create Exchange shadow tomcat-kt-wgadz in namespace default
5:45PM INF Client address 30.5.124.111
5:45PM INF Deploying shadow deployment tomcat-kt-wgadz in namespace default

5:45PM INF Shadow Pod status is Pending
5:45PM INF Shadow Pod status is Running
5:45PM INF Shadow is ready.
5:45PM INF Success deploy proxy deployment tomcat-kt-wgadz in namespace default

5:45PM INF remote 172.16.0.62 forward to local 8080
ssh: connect to host 127.0.0.1 port 2262: Connection refused
Forwarding from 127.0.0.1:2262 -> 22
Forwarding from [::1]:2262 -> 22
panic: sync: negative WaitGroup counter

goroutine 40 [running]:
sync.(*WaitGroup).Add(0xc000392c40, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:99
github.com/alibaba/kt-connect/pkg/kt/connect.remotePortForward.func1(0xc000123820, 0x1b, 0x20c7c35, 0x7, 0xc00045ca20, 0x20, 0x8d6, 0xc00032f600, 0xc0004c4290, 0xc000392c40)
        /Users/yunlong/go/src/github.com/alibaba/kt-connect/pkg/kt/connect/inbound.go:52 +0xda
created by github.com/alibaba/kt-connect/pkg/kt/connect.remotePortForward
        /Users/yunlong/go/src/github.com/alibaba/kt-connect/pkg/kt/connect/inbound.go:49 +0x2e3
exit status 2
```

**Comment by zeusro** [comment]
> ssh.ForwardRemoteRequestToLocal should run after kubectl.PortForward is ready. Otherwise the ssh connection with failed.
> 
> ```
> 5:45PM INF 'KT Connect' not runing, you can only access local app from cluster
> 5:45PM INF Create Exchange shadow tomcat-kt-wgadz in namespace default
> 5:45PM INF Client address 30.5.124.111
> 5:45PM INF Deploying shadow deployment tomcat-kt-wgadz in namespace default
> 
> 5:45PM INF Shadow Pod status is Pending
> 5:45PM INF Shadow Pod status is Running
> 5:45PM INF Shadow is ready.
> 5:45PM INF Success deploy proxy deployment tomcat-kt-wgadz in namespace default
> 
> 5:45PM INF remote 172.16.0.62 forward to local 8080
> ssh: connect to host 127.0.0.1 port 2262: Connection refused
> Forwarding from 127.0.0.1:2262 -> 22
> Forwarding from [::1]:2262 -> 22
> panic: sync: negative WaitGroup counter
> 
> goroutine 40 [running]:
> sync.(*WaitGroup).Add(0xc000392c40, 0xffffffffffffffff)
>         /usr/local/go/src/sync/waitgroup.go:74 +0x139
> sync.(*WaitGroup).Done(...)
>         /usr/local/go/src/sync/waitgroup.go:99
> github.com/alibaba/kt-connect/pkg/kt/connect.remotePortForward.func1(0xc000123820, 0x1b, 0x20c7c35, 0x7, 0xc00045ca20, 0x20, 0x8d6, 0xc00032f600, 0xc0004c4290, 0xc000392c40)
>         /Users/yunlong/go/src/github.com/alibaba/kt-connect/pkg/kt/connect/inbound.go:52 +0xda
> created by github.com/alibaba/kt-connect/pkg/kt/connect.remotePortForward
>         /Users/yunlong/go/src/github.com/alibaba/kt-connect/pkg/kt/connect/inbound.go:49 +0x2e3
> exit status 2
> ```

Sorry,I forget `wg.Add(1)`,could you please try again when you are available ?

**Comment by zeusro** [comment]
```go
     wg.Add(1)
	go func(wg *sync.WaitGroup) {
		portforward := kubectl.PortForward(kubeconfig, namespace, target, localSSHPort)
		err = exec.BackgroundRun(portforward, "exchange port forward to local", debug)
		wg.Done()
	}(&wg)
```

**Comment by yunlzheng** [comment]
i will test it.

**Comment by yunlzheng** [comment]
> ```go
>      wg.Add(1)
> 	go func(wg *sync.WaitGroup) {
> 		portforward := kubectl.PortForward(kubeconfig, namespace, target, localSSHPort)
> 		err = exec.BackgroundRun(portforward, "exchange port forward to local", debug)
> 		wg.Done()
> 	}(&wg)
> ```

@zeusro it's work well. cool

**Comment by zeusro** [comment]
> > ```go
> >      wg.Add(1)
> > 	go func(wg *sync.WaitGroup) {
> > 		portforward := kubectl.PortForward(kubeconfig, namespace, target, localSSHPort)
> > 		err = exec.BackgroundRun(portforward, "exchange port forward to local", debug)
> > 		wg.Done()
> > 	}(&wg)
> > ```
> 
> @zeusro it's work well. cool. Create a new pull request?

You're a warrior, you deserve that code. 

You can consider these codes as my gift to you.
