### ISSUE TITLE
can't clean up k8s resource of ktctl

### ISSUE THREAD

**Issue by mojo-zd** [alibaba/kt-connect#96]
**Describe the bug**
double to execute `ctr + c`  interrupt the program。the k8s resource of ktctl did't clean up

**Environment (please complete the following information):**
 - OS:  Mac Catalina
 - Kubernetes v1.16.4
 - KT Version kt-0.0.11

**Comment by zeusro** [comment]
ctrl + c 
的时候有个退出信号的,你的退出信号是什么

**Comment by zeusro** [comment]
https://github.com/alibaba/kt-connect/pull/97

**Comment by linfan** [comment]
ctrl + c will now handle resource pureness correctly.
beside, ktctl clean command could polyfill the worst case.
